document.addEventListener('DOMContentLoaded', function () {
    var input = document.getElementById('villeInput');
    var dropdownContent = document.getElementById('dropdownContent');
    var villeLink = document.getElementById('villeLink');

    // Tableau de liens de villes
    var cityLinks = [
        { name: 'Baccarat', url: '../../../laPosteDeLancienneFrance/Villes B/Baccarat/baccarat.html' },
        { name: 'Bagneres de Bigorre', url: '../../../laPosteDeLancienneFrance/Villes B/Bagneres/bagneres.html' },
        { name: 'Bagneres de Luchon', url: '../../../laPosteDeLancienneFrance/Villes B/Bagneres30/bagneres.html' },
        { name: 'Bagnols', url: '../../../laPosteDeLancienneFrance/Villes B/Bagnols/bagnols.html' },
        { name: 'Bailleul', url: '../../../laPosteDeLancienneFrance/Villes B/Bailleul/bailleul.html' },
        { name: 'Bain', url: '../../../laPosteDeLancienneFrance/Villes B/Bain/bain.html' },
        { name: 'Bains', url: '../../../laPosteDeLancienneFrance/Villes B/Bains/Bains.html' },
        { name: 'Baisieux', url: '../../../laPosteDeLancienneFrance/Villes B/Baisieux/Baisieux.html' },
        { name: 'Balleroy', url: '../../../laPosteDeLancienneFrance/Villes B/Balleroy/Balleroy.html' },
        { name: 'Bapaume', url: '../../../laPosteDeLancienneFrance/Villes B/Bapaume/Bapaume.html' },
        { name: 'Bar le Duc', url: '../../../laPosteDeLancienneFrance/Villes B/BarLeDuc/BarLeDuc.html' },
        { name: 'Bar sur Aube', url: '../../../laPosteDeLancienneFrance/Villes B/BarSurAube/BarSurAube.html' },
        { name: 'Bar sur Seine', url: '../../../laPosteDeLancienneFrance/Villes B/BarSurSeine/BarSurSeine.html' },
        { name: 'La Baraque sous Gevrey', url: '../../../laPosteDeLancienneFrance/Villes B/Baraque/Baraque.html' },
        { name: 'Barbencon', url: '../../../laPosteDeLancienneFrance/Villes B/Barbencon/Barbencon.html' },
        { name: 'Barbentane', url: '../../../laPosteDeLancienneFrance/Villes B/Barbentane/Barbentane.html' },
        { name: 'Barbezieux', url: '../../../laPosteDeLancienneFrance/Villes B/Barbezieux/Barbezieux.html' },
        { name: 'Barbonne', url: '../../../laPosteDeLancienneFrance/Villes B/Barbonne/Barbonne.html' },
        { name: 'Barcelonette', url: '../../../laPosteDeLancienneFrance/Villes B/Barcelonette/Barcelonette.html' },
        { name: 'Bareges', url: '../../../laPosteDeLancienneFrance/Villes B/Bareges/Bareges.html' },
        { name: 'Barentin', url: '../../../laPosteDeLancienneFrance/Villes B/Barentin/Barentin.html' },
        { name: 'Barjac', url: '../../../laPosteDeLancienneFrance/Villes B/Barjac/Barjac.html' },
        { name: 'Barjols', url: '../../../laPosteDeLancienneFrance/Villes B/Barjols/Barjols.html' },
        { name: 'Barreaux', url: '../../../laPosteDeLancienneFrance/Villes B/BarreauxBarreaux/.html' },
        { name: 'La Barre', url: '../../../laPosteDeLancienneFrance/Villes B/Barre/Barre.html' },
        { name: 'La Bassee', url: '../../../laPosteDeLancienneFrance/Villes B/Basses/Basses.html' },
        { name: 'Bassou', url: '../../../laPosteDeLancienneFrance/Villes B/Bassou/Bassou.html' },
        { name: 'Bastia', url: '../../../laPosteDeLancienneFrance/Villes B/Bastia/Bastia.html' },
        { name: 'Bauge', url: '../../../laPosteDeLancienneFrance/Villes B/Bauge/Bauge.html' },
        { name: 'Baume les Dames', url: '../../../laPosteDeLancienneFrance/Villes B/Baume/Baume.html' },
        { name: 'Bavay', url: '../../../laPosteDeLancienneFrance/Villes B/Bavay/Bavay.html' },
        { name: 'Bayeux', url: '../../../laPosteDeLancienneFrance/Villes B/Bayeux/Bayeux.html' },
        { name: 'Bayonne', url: '../../../laPosteDeLancienneFrance/Villes B/Bayonne/Bayonne.html' },
        { name: 'Bazas', url: '../../../laPosteDeLancienneFrance/Villes B/Bazas/Bazas.html' },
        { name: 'Beaucaire', url: '../../../laPosteDeLancienneFrance/Villes B/Beaucaire/Beaucaire.html' },
        { name: 'Beaufort', url: '../../../laPosteDeLancienneFrance/Villes B/Beaufort/Beaufort.html' },
        { name: 'Beaugency', url: '../../../laPosteDeLancienneFrance/Villes B/Beaugency/Beaugency.html' },
        { name: 'Beaujeu', url: '../../../laPosteDeLancienneFrance/Villes B/Beaujeu/Beaujeu.html' },
        { name: 'Beaulieu (36)', url: '../../../laPosteDeLancienneFrance/Villes B/Beaulieu36/Beaulieu36.html' },
        { name: 'Beaulieu (18)', url: '../../../laPosteDeLancienneFrance/Villes B/Beaulieu18/Beaulieu18.html' },
        { name: 'Beaulieu79', url: '../../../laPosteDeLancienneFrance/Villes B/Beaulieu (79)/Beaulieu (79).html' },
        { name: 'Beaumont de Lomagne', url: '../../../laPosteDeLancienneFrance/Villes B/Beaumont30/Beaumont30.html' },
        { name: 'Beaumont de Roger', url: '../../../laPosteDeLancienneFrance/Villes B/Beaumont26/Beaumont26.html' },
        { name: 'Beaumont le Viconte', url: '../../../laPosteDeLancienneFrance/Villes B/Beaumont71/Beaumont71.html' },
        { name: 'Beaumont sur oise', url: '../../../laPosteDeLancienneFrance/Villes B/Beaumont72/Beaumont72.html' },
        { name: 'Beaune', url: '../../../laPosteDeLancienneFrance/Villes B/Beaune/baune.html' },
        { name: 'Beaupreau', url: '../../../laPosteDeLancienneFrance/Villes B/Beaupreau/Beaupreau.html' },
        { name: 'Beaurepaire', url: '../../../laPosteDeLancienneFrance/Villes B/Beaurepaire/Beaurepaire.html' },
        { name: 'Le Beausset', url: '../../../laPosteDeLancienneFrance/Villes B/Beausset/Beausset.html' },
        { name: 'Beauvais', url: '../../../laPosteDeLancienneFrance/Villes B/Beauvais/Beauvais.html' },
        { name: 'Beauvoir sur mer', url: '../../../laPosteDeLancienneFrance/Villes B/Beauvoir/Beauvoir.html' },
        { name: 'Becherel', url: '../../../laPosteDeLancienneFrance/Villes B/Becherel/Becherel.html' },
        { name: 'Bedarieux', url: '../../../laPosteDeLancienneFrance/Villes B/Bedarieux/Bedarieux.html' },
        { name: 'Belfort', url: '../../../laPosteDeLancienneFrance/Villes B/Belfort/Belfort.html' },
        { name: 'Bellac', url: '../../../laPosteDeLancienneFrance/Villes B/Bellac/Bellac.html' },
        { name: 'Belle Isle en Mer', url: '../../../laPosteDeLancienneFrance/Villes B/Belle/belleIsleEnMer.html' },
        { name: 'Belle Isle en Terre', url: '../../../laPosteDeLancienneFrance/Villes B/BelleIsleEnTerre/belleIsleEnTerre.html' },
        { name: 'Bellegarde', url: '../../../laPosteDeLancienneFrance/Villes B/Bellegarde/Bellegarde.html' },
        { name: 'Bellemare', url: '../../../laPosteDeLancienneFrance/Villes B/Bellemare/Bellemare.html' },
        { name: 'Belleme', url: '../../../laPosteDeLancienneFrance/Villes B/Belleme/Belleme.html' },
        { name: 'Belleville sur Saone', url: '../../../laPosteDeLancienneFrance/Villes B/Belleville/Belleville.html' },
        { name: 'Belley', url: '../../../laPosteDeLancienneFrance/Villes B/Belley/Belley.html' },
        { name: 'Belpech', url: '../../../laPosteDeLancienneFrance/Villes B/Belpech/Belpech.html' },
        { name: 'Belves', url: '../../../laPosteDeLancienneFrance/Villes B/Belves/Belves.html' },
        { name: 'Benfeld', url: '../../../laPosteDeLancienneFrance/Villes B/Benfeld/Benfeld.html' },
        { name: 'Bergerac', url: '../../../laPosteDeLancienneFrance/Villes B/Bergerac/Bergerac.html' },
        { name: 'Bergues', url: '../../../laPosteDeLancienneFrance/Villes B/Bergues/Bergues.html' },
        { name: 'Bernay', url: '../../../laPosteDeLancienneFrance/Villes B/Bernay/Bernay.html' },
        { name: 'Besancon', url: '../../../laPosteDeLancienneFrance/Villes B/Besancon/Besancon.html' },
        { name: 'Besse', url: '../../../laPosteDeLancienneFrance/Villes B/Besse/Besse.html' },
        { name: 'Bessines', url: '../../../laPosteDeLancienneFrance/Villes B/Bessines/Bessines.html' },
        { name: 'Bethleem', url: '../../../laPosteDeLancienneFrance/Villes B/Bethleem/Bethleem.html' },
        { name: 'Béthune', url: '../../../laPosteDeLancienneFrance/Villes B/Béthune/Béthune.html' },
        { name: 'Bézier', url: '../../../laPosteDeLancienneFrance/Villes B/Bézier/Bézier.html' },
        { name: 'Billom', url: '../../../laPosteDeLancienneFrance/Villes B/Billom/billom.html' },
        { name: 'Binche', url: '../../../laPosteDeLancienneFrance/Villes B/Binche/Binche.html' },
        { name: 'Bitche', url: '../../../laPosteDeLancienneFrance/Villes B/Bitche/Bitche.html' },
        { name: 'Blain', url: '../../../laPosteDeLancienneFrance/Villes B/Blain/Blain.html' },
        { name: 'Blamont (24)', url: '../../../laPosteDeLancienneFrance/Villes B/Blamont24/blamont24.html' },
        { name: 'Blamont (52)', url: '../../../laPosteDeLancienneFrance/Villes B/Blamont52/blamont52.html' },
        { name: 'Le Blanc', url: '../../../laPosteDeLancienneFrance/Villes B/Blanc/Blanc.html' },
        { name: 'Blanzac', url: '../../../laPosteDeLancienneFrance/Villes B/Blanzac/Blanzac.html' },
        { name: 'Blaye', url: '../../../laPosteDeLancienneFrance/Villes B/Blaye/Blaye.html' },
        { name: 'Bléré', url: '../../../laPosteDeLancienneFrance/Villes B/Bléré/Bléré.html' },
        { name: 'Blois', url: '../../../laPosteDeLancienneFrance/Villes B/Blois/Blois.html' },
        { name: 'Blosseville', url: '../../../laPosteDeLancienneFrance/Villes B/Blosseville/Blosseville.html' },
        { name: 'Besançon', url: '../../../laPosteDeLancienneFrance/Villes B/Besançon/Besançon.html' },
        { name: 'Boiscommun', url: '../../../laPosteDeLancienneFrance/Villes B/Boiscommun/Boiscommun.html' },
        { name: 'Boissy St Leger', url: '../../../laPosteDeLancienneFrance/Villes B/Boissy/Boissy.html' },
        { name: 'Bolbec', url: '../../../laPosteDeLancienneFrance/Villes B/Bolbec/Bolbec.html' },
        { name: 'Le Bolhard', url: '../../../laPosteDeLancienneFrance/Villes B/Bolhard/Bolhard.html' },
        { name: 'Boncourt', url: '../../../laPosteDeLancienneFrance/Villes B/Boncourt/Boncourt.html' },
        { name: 'Bondy', url: '../../../laPosteDeLancienneFrance/Villes B/Bondy/Bondy.html' },
        { name: 'Bonifacio', url: '../../../laPosteDeLancienneFrance/Villes B/Bonifacio/Bonifacio.html' },
        { name: 'Bonnelles', url: '../../../laPosteDeLancienneFrance/Villes B/Bonnelles/Bonnelles.html' },
        { name: 'Bonnetable', url: '../../../laPosteDeLancienneFrance/Villes B/Bonnetable/Bonnetable.html' },
        { name: 'Bonneval', url: '../../../laPosteDeLancienneFrance/Villes B/Bonneval/Bonneval.html' },
        { name: 'Bonnieres', url: '../../../laPosteDeLancienneFrance/Villes B/Bonnieres/Bonnieres.html' },
        { name: 'Bonny', url: '../../../laPosteDeLancienneFrance/Villes B/Bonny/Bonny.html' },
        { name: 'Le Bordeau de Vigny', url: '../../../laPosteDeLancienneFrance/Villes B/Bordeau/Bordeau.html' },
        { name: 'Petite poste de Bordeaux', url: '../../../laPosteDeLancienneFrance/Villes B/Bordeauxpp/Bordeauxpp.html' },
        { name: 'Bort', url: '../../../laPosteDeLancienneFrance/Villes B/Bort/Bort.html' },
        { name: 'Bouchain', url: '../../../laPosteDeLancienneFrance/Villes B/Bouchain/Bouchain.html' },
        { name: 'Boucoiran', url: '../../../laPosteDeLancienneFrance/Villes B/Boucoiran/Boucoiran.html' },
        { name: 'Bouillon', url: '../../../laPosteDeLancienneFrance/Villes B/Bouillon/Bouillon.html' },
        { name: 'Boulay', url: '../../../laPosteDeLancienneFrance/Villes B/Boulay/Boulay.html' },
        { name: 'Boulogne', url: '../../../laPosteDeLancienneFrance/Villes B/Boulogne/Boulogne.html' },
        { name: 'Boulogne sur Mer', url: '../../../laPosteDeLancienneFrance/Villes B/BoulogneSurMer/BoulogneSurMer.html' },
        { name: 'Boulou', url: '../../../laPosteDeLancienneFrance/Villes B/Boulou/Boulou.html' },
        { name: 'Bouquenon', url: '../../../laPosteDeLancienneFrance/Villes B/Bouquenon/Bouquenon.html' },
        { name: 'Bourbon L Archambault', url: '../../../laPosteDeLancienneFrance/Villes B/Bourbon/Bourbon.html' },
        { name: 'Bourbon Lancy', url: '../../../laPosteDeLancienneFrance/Villes B/BourbonLancy/BourbonLancy.html' },
        { name: 'Bourbonne', url: '../../../laPosteDeLancienneFrance/Villes B/Bourbonne/Bourbonne.html' },
        { name: 'Bourbourg', url: '../../../laPosteDeLancienneFrance/Villes B/Bourbourg/Bourbourg.html' },
        { name: 'Bourdeilles', url: '../../../laPosteDeLancienneFrance/Villes B/Bourdeilles/Bourdeilles.html' },
        { name: 'Bourg Argental', url: '../../../laPosteDeLancienneFrance/Villes B/BourgArgental/BourgArgental.html' },
        { name: 'Bourdon', url: '../../../laPosteDeLancienneFrance/Villes B/Bourdon/Bourdon.html' },
        { name: 'Bourg D Oisans', url: '../../../laPosteDeLancienneFrance/Villes B/BourgDoisan/BourgDoisan.html' },
        { name: 'Bourg en Bresse', url: '../../../laPosteDeLancienneFrance/Villes B/BourgEnBresse/BourgEnBresse.html' },
        { name: 'Bourg en Guyenne', url: '../../../laPosteDeLancienneFrance/Villes B/BourgEnGuyenne/BourgEnGuyenne.html' },
        { name: 'Bourg la Reine', url: '../../../laPosteDeLancienneFrance/Villes B/BourgLaReine/BourgLaReine.html' },
        { name: 'Bourg St Andeol', url: '../../../laPosteDeLancienneFrance/Villes B/BourgStAndeol/BourgStAndeol.html' },
        { name: 'Bourgachard', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgachard/Bourgachard.html' },
        { name: 'Bourganeuf', url: '../../../laPosteDeLancienneFrance/Villes B/Bourganeuf/Bourganeuf.html' },
        { name: 'Bourges', url: '../../../laPosteDeLancienneFrance/Villes B/Bourges/Bourges.html' },
        { name: 'Le bourget', url: '../../../laPosteDeLancienneFrance/Villes B/Bourget/Bourget.html' },
        { name: 'Bourgneuf', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgneuf/Bourgneuf.html' },
        { name: 'Bourgneuf en Retz', url: '../../../laPosteDeLancienneFrance/Villes B/BourgneufEnRetz/BourgneufEnRetz.html' },
        { name: 'Bourgoin', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgoin/Bourgoin.html' },
        { name: 'Bourgtheroulde', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgtheroulde/Bourgtheroulde.html' },
        { name: 'Bourgueil', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgueil/Bourgueil.html' },
        { name: 'Bourmont', url: '../../../laPosteDeLancienneFrance/Villes B/Bourmont/Bourmont.html' },
        { name: 'Boussac', url: '../../../laPosteDeLancienneFrance/Villes B/Boussac/Boussac.html' },
        { name: 'Bouxwiller', url: '../../../laPosteDeLancienneFrance/Villes B/Bouxwiller/Bouxwiller.html' },
        { name: 'Bouzonville', url: '../../../laPosteDeLancienneFrance/Villes B/Bouzonville/Bouzonville.html' },
        { name: 'Boynes', url: '../../../laPosteDeLancienneFrance/Villes B/Boynes/Boynes.html' },
        { name: 'Braisne', url: '../../../laPosteDeLancienneFrance/Villes B/Braisne/Braisne.html' },
        { name: 'Bray sur Seine', url: '../../../laPosteDeLancienneFrance/Villes B/Bray/Bray.html' },
        { name: 'Brecey', url: '../../../laPosteDeLancienneFrance/Villes B/Brecey/Brecey.html' },
        { name: 'Bressuire', url: '../../../laPosteDeLancienneFrance/Villes B/Bressuire/Bressuire.html' },
        { name: 'Brest', url: '../../../laPosteDeLancienneFrance/Villes B/Brest/Brest.html' },
        { name: 'La Breteche', url: '../../../laPosteDeLancienneFrance/Villes B/Breteche/Breteche.html' },
        { name: 'Breteuil (26)', url: '../../../laPosteDeLancienneFrance/Villes B/Breteuil26/Breteuil26.html' },
        { name: 'Breteuil (58)', url: '../../../laPosteDeLancienneFrance/Villes B/Breteuil58/Breteuil58.html' },
        { name: 'Brezolle', url: '../../../laPosteDeLancienneFrance/Villes B/Brezolle/Brezolle.html' },
        { name: 'Briancon', url: '../../../laPosteDeLancienneFrance/Villes B/Briancon/Briancon.html' },
        { name: 'Briare', url: '../../../laPosteDeLancienneFrance/Villes B/Briare/Briare.html' },
        { name: 'Brie comte Robert', url: '../../../laPosteDeLancienneFrance/Villes B/Brie/Brie.html' },
        { name: 'Brienne le Château', url: '../../../laPosteDeLancienneFrance/Villes B/Brienne/Brienne.html' },
        { name: 'Brienon L Archeveque', url: '../../../laPosteDeLancienneFrance/Villes B/Brienon/Brienon.html' },
        { name: 'Briey', url: '../../../laPosteDeLancienneFrance/Villes B/Briey/Briey.html' },
        { name: 'Brignoles', url: '../../../laPosteDeLancienneFrance/Villes B/Brignoles/Brignoles.html' },
        { name: 'Brillac', url: '../../../laPosteDeLancienneFrance/Villes B/Brillac/Brillac.html' },
        { name: 'Brionne', url: '../../../laPosteDeLancienneFrance/Villes B/Brionne/Brionne.html' },
        { name: 'Brioude', url: '../../../laPosteDeLancienneFrance/Villes B/Brioude/Brioude.html' },
        { name: 'Brisach', url: '../../../laPosteDeLancienneFrance/Villes B/Brisach/Brisach.html' },
        { name: 'Brissac', url: '../../../laPosteDeLancienneFrance/Villes B/Brissac/Brissac.html' },
        { name: 'Brive', url: '../../../laPosteDeLancienneFrance/Villes B/Brive/Brive.html' },
        { name: 'Broons', url: '../../../laPosteDeLancienneFrance/Villes B/Broons/Broons.html' },
        { name: 'Brou', url: '../../../laPosteDeLancienneFrance/Villes B/Brou/Brou.html' },
        { name: 'Brouage', url: '../../../laPosteDeLancienneFrance/Villes B/Brouage/Brouage.html' },
        { name: 'Brunoy', url: '../../../laPosteDeLancienneFrance/Villes B/Brunoy/Brunoy.html' },
        { name: 'Bruyeres', url: '../../../laPosteDeLancienneFrance/Villes B/Bruyeres/Bruyeres.html' },
        { name: 'Buchy', url: '../../../laPosteDeLancienneFrance/Villes B/Buchy/Buchy.html' },
        { name: 'Le Bugue', url: '../../../laPosteDeLancienneFrance/Villes B/Buis/Buis.html' },
        { name: 'La Buissiere', url: '../../../laPosteDeLancienneFrance/Villes B/Buissieres/Buissieres.html' },
        { name: 'Buzancais', url: '../../../laPosteDeLancienneFrance/Villes B/Buzancais/Buzancais.html' },
        { name: 'Buzancy', url: '../../../laPosteDeLancienneFrance/Villes B/Buzancy/Buzancy.html' },
        
        // Ajoutez d'autres villes ici
    ];

    // Initialisation des liens de ville
    for (var i = 0; i < cityLinks.length; i++) {
        var link = document.createElement('a');
        link.href = cityLinks[i].url;
        link.textContent = cityLinks[i].name;
        dropdownContent.appendChild(link);
    }

    input.addEventListener('input', function () {
        var filter = input.value.toLowerCase();
        var links = dropdownContent.getElementsByTagName('a');

        for (var i = 0; i < links.length; i++) {
            var city = links[i].textContent.toLowerCase();
            links[i].style.display = city.includes(filter) ? '' : 'none';
        }
    });

    dropdownContent.addEventListener('click', function (event) {
        var target = event.target;
        if (target.tagName === 'A') {
            villeLink.innerHTML = ' &emsp;&emsp;' + target.textContent + '<i class="fas fa-caret-down"></i>';
            window.location.href = target.href;
        }
    });
});