document.addEventListener('DOMContentLoaded', function () {
    var input = document.getElementById('villeInput');
    var dropdownContent = document.getElementById('dropdownContent');
    var villeLink = document.getElementById('villeLink');

    // Tableau de liens de villes
    var cityLinks = [
        { name: 'Cadenet', url: '../../../laPosteDeLancienneFrance/Villes_C/Cadenet/cadenet.html' },
        { name: 'Cadillac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cadillac/cadillac.html' },
        { name: 'Caen', url: '../../../laPosteDeLancienneFrance/Villes_C/Caen/caen.html' },
        { name: 'Cahors', url: '../../../laPosteDeLancienneFrance/Villes_C/Cahors/cahors.html' },
        { name: 'Calais', url: '../../../laPosteDeLancienneFrance/Villes_C/Calais/calais.html' },
        { name: 'Calvi', url: '../../../laPosteDeLancienneFrance/Villes_C/Calvi/calvi.html' },
        { name: 'Cahusac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cahusac/cahusac.html' },
        { name: 'Calvisson', url: '../../../laPosteDeLancienneFrance/Villes_C/Calvisson/calvisson.html' },
        { name: 'Camaret', url: '../../../laPosteDeLancienneFrance/Villes_C/Camaret/camaret.html' },
        { name: 'Cambrai', url: '../../../laPosteDeLancienneFrance/Villes_C/Cambrai/cambrai.html' },
        { name: 'Cande', url: '../../../laPosteDeLancienneFrance/Villes_C/Cande/cande.html' },
        { name: 'Cannes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cannes/cannes.html' },
        { name: 'Cany', url: '../../../laPosteDeLancienneFrance/Villes_C/Cany/cany.html' },
        { name: 'Caraman', url: '../../../laPosteDeLancienneFrance/Villes_C/Caraman/caraman.html' },
        { name: 'Carcassonne', url: '../../../laPosteDeLancienneFrance/Villes_C/Carcassonne/carcassonne.html' },
        { name: 'Carentan', url: '../../../laPosteDeLancienneFrance/Villes_C/Carentan/carentan.html' },
        { name: 'Carhaix', url: '../../../laPosteDeLancienneFrance/Villes_C/Carhaix/carhaix.html' },
        { name: 'Carignan', url: '../../../laPosteDeLancienneFrance/Villes_C/Carignan/carignan.html' },
        { name: 'La Carla Bayle', url: '../../../laPosteDeLancienneFrance/Villes_C/CarlaBayle/carlaBayle.html' },
        { name: 'Carpentras', url: '../../../laPosteDeLancienneFrance/Villes_C/Carpentras/carpentras.html' },
        { name: 'Carrouge', url: '../../../laPosteDeLancienneFrance/Villes_C/Carrouge/carrouge.html' },
        { name: 'Carvin', url: '../../../laPosteDeLancienneFrance/Villes_C/Carvin/carvin.html' },
        { name: 'Casal', url: '../../../laPosteDeLancienneFrance/Villes_C/Casal/casal.html' },
        { name: 'Cassel', url: '../../../laPosteDeLancienneFrance/Villes_C/Cassel/cassel.html' },
        { name: 'Cassis', url: '../../../laPosteDeLancienneFrance/Villes_C/Cassis/cassis.html' },
        { name: 'Castelfranc', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelfranc/castelfranc.html' },
        { name: 'Castellane', url: '../../../laPosteDeLancienneFrance/Villes_C/Castellane/castellane.html' },
        { name: 'Castelnau de Magnoac', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelnau/castelnau.html' },
        { name: 'Castelnau de Médoc', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelnau32/castelnau32.html' },
        { name: 'Castelnau de Montratier', url: '../../../laPosteDeLancienneFrance/Villes_C/castelnau44/castelnau44.html' },
        { name: 'Castelnaudary', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelnaudary/castelnaudary.html' },
        { name: 'Castelsarrasin', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelsarrasin/castelsarrasin.html' },
        { name: 'Castillon', url: '../../../laPosteDeLancienneFrance/Villes_C/Castillon/castillon.html' },
        { name: 'Castre', url: '../../../laPosteDeLancienneFrance/Villes_C/Castre/castre.html' },
        { name: 'Castre en Guyenne', url: '../../../laPosteDeLancienneFrance/Villes_C/Castre32/castresEnGuyenne.html.html' },
        { name: 'Le-Cateau-Cambresis', url: '../../../laPosteDeLancienneFrance/Villes_C/Le-Cateau-Cambresis/lecateauCambresis.html' },
        { name: 'Le-Catelet', url: '../../../laPosteDeLancienneFrance/Villes_C/Le-Catelet/lecatelet.html' },
        { name: 'Caudebec', url: '../../../laPosteDeLancienneFrance/Villes L/Caudebec/caudebec.html' },
        { name: 'Caudrot', url: '../../../laPosteDeLancienneFrance/Villes_C/Caudrot/caudrot.html' },
        { name: 'Caudry', url: '../../../laPosteDeLancienneFrance/Villes_C/Caudry/caudry.html' },
        { name: 'Caussade', url: '../../../laPosteDeLancienneFrance/Villes_C/Caussade/caussade.html' },
        { name: 'Cauterets', url: '../../../laPosteDeLancienneFrance/Villes_C/Cauterets/cauterets.html' },
        { name: 'Cavaillon', url: '../../../laPosteDeLancienneFrance/Villes_C/Cavaillon/cavaillon.html' },
        { name: 'Cavignac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cavignac/cavignac.html' },
        { name: 'Caylus', url: '../../../laPosteDeLancienneFrance/Villes_C/Caylus/caylus.html' },
        { name: 'Cazeres', url: '../../../laPosteDeLancienneFrance/Villes_C/Cazeres/cazeres.html' },
        { name: 'Cercles', url: '../../../laPosteDeLancienneFrance/Villes_C/Cercles/cercles.html' },
        { name: 'Cerdon', url: '../../../laPosteDeLancienneFrance/Villes_C/Cerdon/cerdon.html' },
        { name: 'Céret', url: '../../../laPosteDeLancienneFrance/Villes_C/Ceret/ceret.html' },
        { name: 'Cernay', url: '../../../laPosteDeLancienneFrance/Villes_C/Cernay/cernay.html' },
        { name: 'Cervione', url: '../../../laPosteDeLancienneFrance/Villes_C/Cervione/cervione.html' },
        { name: 'Cette', url: '../../../laPosteDeLancienneFrance/Villes_C/Cette/cette.html' },
        { name: 'Chabanais', url: '../../../laPosteDeLancienneFrance/Villes_C/Chabanais/chabanais.html' },
        { name: 'Chablis', url: '../../../laPosteDeLancienneFrance/Villes_C/Chablis/chablis.html' },
        { name: 'Chagny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chagny/chagny.html' },
        { name: 'La-Chaise-Dieu', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Chaise-Dieu/laChaiseDieu.html' },
        { name: 'Chalabre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalabre/chalabre.html' },
        { name: 'Chalamont', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalamont/chalamont.html' },
        { name: 'Le-Chalard', url: '../../../laPosteDeLancienneFrance/Villes_C/Le-Chalard/leChalard.html' },
        { name: 'La-Chalaure', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Chalaure/laChalaure.html' },
        { name: 'Challans', url: '../../../laPosteDeLancienneFrance/Villes_C/Challans/challans.html' },
        { name: 'Chalon-Sur-Saone', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalon-Sur-Saone/chalonSurSaone.html' },
        { name: 'Chalons-Sur-Marne', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalons-Sur-Marne/chalonsSurMarne.html' },
        { name: 'Chalus', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalus/chalus.html' },
        { name: 'Chambly', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambly/chambly.html' },
        { name: 'Chambon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambon/chambon.html' },
        { name: 'Chambord', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambord/chambord.html' },
        { name: 'Chambrais', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambrais/chambrais.html' },
        { name: 'Champagnole', url: '../../../laPosteDeLancienneFrance/Villes_C/Champagnole/champagnole.html' },
        { name: 'Champigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Champigny/champigny.html' },
        { name: 'Champlitte', url: '../../../laPosteDeLancienneFrance/Villes_C/Champlitte/champlitte.html' },
        { name: 'Champrond', url: '../../../laPosteDeLancienneFrance/Villes_C/Champrond/champrond.html' },
        { name: 'Chanceaux', url: '../../../laPosteDeLancienneFrance/Villes_C/Chanceaux/chanceaux.html' },
        { name: 'Chanteloube', url: '../../../laPosteDeLancienneFrance/Villes_C/Chanteloube/chanteloube.html' },
        { name: 'Chantilly', url: '../../../laPosteDeLancienneFrance/Villes_C/Chantilly/chantilly.html' },
        { name: 'Chantonnay', url: '../../../laPosteDeLancienneFrance/Villes_C/Chantonnay/chantonnay.html' },
        { name: 'Chaource', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaource/chaource.html' },
        { name: 'Charente', url: '../../../laPosteDeLancienneFrance/Villes_C/Charente/charante.html' },
        { name: 'Charenton', url: '../../../laPosteDeLancienneFrance/Villes_C/Charenton/charenton.html' },
        { name: 'La Charite', url: '../../../laPosteDeLancienneFrance/Villes_C/Charite/charite.html' },
        { name: 'Charlemont', url: '../../../laPosteDeLancienneFrance/Villes_C/Charlemont/charlemont.html' },
        { name: 'Charleroi', url: '../../../laPosteDeLancienneFrance/Villes_C/Charleroi/charleroi.html' },
        { name: 'Charleville', url: '../../../laPosteDeLancienneFrance/Villes_C/Charleville/charleville.html' },
        { name: 'Charly', url: '../../../laPosteDeLancienneFrance/Villes_C/Charly/charly.html' },
        { name: 'Charmes', url: '../../../laPosteDeLancienneFrance/Villes_C/Charmes/charmes.html' },
        { name: 'Charolles', url: '../../../laPosteDeLancienneFrance/Villes_C/Charolles/charolles.html' },
        { name: 'Charost', url: '../../../laPosteDeLancienneFrance/Villes_C/Charost/charost.html' },
        { name: 'Chartre-Sur-Le-Loire', url: '../../../laPosteDeLancienneFrance/Villes_C/Chartre-Sur-Le-Loire/chartreSurLeLoir.html' },
        { name: 'Chartres', url: '../../../laPosteDeLancienneFrance/Villes_C/Chartres/chartres.html' },
        { name: 'La-Chataigneraie', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Chataigneraie/laChataigneraie.html' },
        { name: 'Chateau-chalon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-chalon/chateauChalon.html' },
        { name: 'Chateau-Chinon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Chinon/chateauChinon.html' },
        { name: 'Chateau-Du-Loire', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Du-Loire/chateauDuLoir.html' },
        { name: 'Chateau-Gontier', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Gontier/chateauGontier.html' },
        { name: 'Chateau-Landon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Landon/chateauLandon.html' },
        { name: 'Chateau-Porcien', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Porcien/chateauPorcien.html' },
        { name: 'Chateau-Renault', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Renault/chateauRenault.html' },
        { name: 'Chateau-Salins', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Salins/chateauSalins.html' },
        { name: 'Chateau-Thierry', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Thierry/chateauThierry.html' },
        { name: 'Chateau-Villain', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau-Villain/chateauVillain.html' },
        { name: 'Chateaubriant', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaubriant/chateaubriant.html' },
        { name: 'Chateaudun', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaudun/chateaudun.html' },
        { name: 'Chateaulin', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaulin/chateaulin.html' },
        { name: 'Chateaumeillant', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaumeillant/chateaumeillant.html' },
        { name: 'Chateauneuf', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf/chateauneuf.html' },
        { name: 'Chateauneuf-de-Bretagne', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf-de-Bretagne/chateaunefDeBretagne.html' },
        { name: 'Chateauneuf-Sur-Cher', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf-Sur-Cher/chateaneufsurCher.html' },
        { name: 'Chateauneuf-En-Thymerais', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf-En-Thymerais/chateaunefEnThymerais.html' },
        { name: 'Chateauroux', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauroux/chateauroux.html' },
        { name: 'Chatel-Sur-Moselle', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatel-Sur-Moselle/chatelSurMoselle.html' },
        { name: 'Chatelaudren', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatelaudren/chatelaudren.html' },
        { name: 'Le-Chatelet-En-Brie', url: '../../../laPosteDeLancienneFrance/Villes_C/Le-Chatelet-En-Brie/leChateletEnBrie.html' },
        { name: 'Le-Catelet', url: '../../../laPosteDeLancienneFrance/Villes_C/Le-Catelet/leCatelet.html' },
        { name: 'Chatellerault', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatellerault/chatellerault.html' },
        { name: 'Chatillon-De-Michaille', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-De-Michaille/chatillonDeMichaille.html' },
        { name: 'Chatillon-Les-Dombes', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-Les-Dombes/chatillonLesDombes.html' },
        { name: 'Chatillon-Sur-Indre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-Sur-Indre/chatillonSurIndre.html' },
        { name: 'Chatillon-Sur-Loing', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-Sur-Loing/chatillonSurLoing.html' },
        { name: 'Chatillon-Sur-Loire', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-Sur-Loire/chatillonSurLoire.html' },
        { name: 'Chatillon-Sur-Marne', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-Sur-Marne/chatillonSurMarne.html' },
        { name: 'Chatillon-Sur-Seine', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-Sur-Seine/chatillonSurSeine.html' },
        { name: 'Chatillon-Sur-Sevre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon-Sur-Sevre/chatillonSurSevre.html' },
        { name: 'Chatou', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatou/chatou.html' },
        { name: 'La-Chatre', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Chatre/laChatre.html' },
        { name: 'Chaudesaigues', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaudesaigues/chaudesaigues.html' },
        { name: 'Chaumes', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaumes/chaumes.html' },
        { name: 'Chaumont-En-Bassigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaumont-En-Bassigny/chaumontEnBassigny.html' },
        { name: 'Chaumont-En-Vexin', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaumont-En-Vexin/chaumontEnVexin.html' },
        { name: 'Chaunai', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaunai/chaunai.html' },
        { name: 'Chauny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chauny/chauny.html' },
        { name: 'La-Chaussee', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Chaussee/laChaussee.html' },
        { name: 'Chauvigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chauvigny/chauvigny.html' },
        { name: 'Chazelles', url: '../../../laPosteDeLancienneFrance/Villes_C/Chazelles/chazelles.html' },
        { name: 'Chef-Boutonne', url: '../../../laPosteDeLancienneFrance/Villes_C/Chef-Boutonne/chefBoutonne.html' },
        { name: 'Chelles', url: '../../../laPosteDeLancienneFrance/Villes_C/Chelles/chelles.html' },
        { name: 'Chemille', url: '../../../laPosteDeLancienneFrance/Villes_C/Chemille/chemille.html' },
        { name: 'Chenerailles', url: '../../../laPosteDeLancienneFrance/Villes_C/Chenerailles/chenerailles.html' },
        { name: 'Cherbourg', url: '../../../laPosteDeLancienneFrance/Villes_C/Cherbourg/cherbourg.html' },
        { name: 'Cheroy', url: '../../../laPosteDeLancienneFrance/Villes_C/Cheroy/cheroy.html' },
        { name: 'Chevilly', url: '../../../laPosteDeLancienneFrance/Villes_C/Chevilly/chevilly.html' },
        { name: 'Chevreuse', url: '../../../laPosteDeLancienneFrance/Villes_C/Chevreuse/chevreuse.html' },
        { name: 'Chezy', url: '../../../laPosteDeLancienneFrance/Villes_C/Chezy/chezy.html' },
        { name: 'Chilleurs', url: '../../../laPosteDeLancienneFrance/Villes_C/Chilleurs/chilleurs.html' },
        { name: 'Chinon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chinon/chinon.html' },
        { name: 'Choisy-Le-Roi', url: '../../../laPosteDeLancienneFrance/Villes_C/Choisy-Le-Roi/choisyLeRoi.html' },
        { name: 'Cholet', url: '../../../laPosteDeLancienneFrance/Villes_C/Cholet/cholet.html' },
        { name: 'Chomerac', url: '../../../laPosteDeLancienneFrance/Villes_C/Chomerac/chomerac.html' },
        { name: 'Chorges', url: '../../../laPosteDeLancienneFrance/Villes_C/Chorges/chorges.html' },
        { name: 'Chouze', url: '../../../laPosteDeLancienneFrance/Villes_C/Chouze/chouze.html' },
        { name: 'Cingetabelle', url: '../../../laPosteDeLancienneFrance/Villes_C/Cingetabelle/cingetabelle.html' },
        { name: 'Cintrey', url: '../../../laPosteDeLancienneFrance/Villes_C/Cintrey/cintrey.html' },
        { name: 'La-Ciotat', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Ciotat/laCiotat.html' },
        { name: 'Cirey-S-Blaise', url: '../../../laPosteDeLancienneFrance/Villes_C/Cirey-S-Blaise/cireySBlaise.html' },
        { name: 'Civray', url: '../../../laPosteDeLancienneFrance/Villes_C/Civray/civray.html' },
        { name: 'Cizay', url: '../../../laPosteDeLancienneFrance/Villes_C/Cizay/cizay.html' },
        { name: 'Clairac', url: '../../../laPosteDeLancienneFrance/Villes_C/Clairac/clairac.html' },
        { name: 'Clairvaux', url: '../../../laPosteDeLancienneFrance/Villes_C/Clairvaux/clairvaux.html' },
        { name: 'Clamecy', url: '../../../laPosteDeLancienneFrance/Villes_C/Clamecy/clamecy.html' },
        { name: 'Claye', url: '../../../laPosteDeLancienneFrance/Villes_C/Claye/Claye.html' },
        { name: 'La-Clayette', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Clayette/laClayette.html' },
        { name: 'Clermont-En-Argonne', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont-En-Argonne/clermontEnArgonne.html' },
        { name: 'Clermont-En-Beauvoisis', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont-En-Beauvoisis/clermontEnBeauvoisis.html' },
        { name: 'Clermont-Ferrand', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont-Ferrand/clermontFerrand.html' },
        { name: 'Clermont-Lodeve', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont-Lodeve/clermontLodeve.html' },
        { name: 'Clerval', url: '../../../laPosteDeLancienneFrance/Villes_C/Clerval/clerval.html' },
        { name: 'Clery', url: '../../../laPosteDeLancienneFrance/Villes_C/Clery/clery.html' },
        { name: 'Clisson', url: '../../../laPosteDeLancienneFrance/Villes_C/Clisson/clisson.html' },
        { name: 'Cloyes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cloyes/cloyes.html' },
        { name: 'Cluny', url: '../../../laPosteDeLancienneFrance/Villes_C/Cluny/cluny.html' },
        { name: 'Cocherel', url: '../../../laPosteDeLancienneFrance/Villes_C/Cocherel/cocherel.html' },
        { name: 'Cognac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cognac/cognac.html' },
        { name: 'Collioure', url: '../../../laPosteDeLancienneFrance/Villes_C/Collioure/collioure.html' },
        { name: 'Coincy', url: '../../../laPosteDeLancienneFrance/Villes_C/Coincy/coincy.html' },
        { name: 'Collobrieres', url: '../../../laPosteDeLancienneFrance/Villes_C/Collobrieres/collobrieres.html' },
        { name: 'Collonges', url: '../../../laPosteDeLancienneFrance/Villes_C/Collonges/collonges.html' },
        { name: 'Colmar', url: '../../../laPosteDeLancienneFrance/Villes_C/Colmar/colmar.html' },
        { name: 'Colmars', url: '../../../laPosteDeLancienneFrance/Villes_C/Colmars/colmars.html' },
        { name: 'Colombey', url: '../../../laPosteDeLancienneFrance/Villes_C/Colombey/colombey.html' },
        { name: 'Combouin', url: '../../../laPosteDeLancienneFrance/Villes_C/Combouin/combouin.html' },
        { name: 'Combourg', url: '../../../laPosteDeLancienneFrance/Villes_C/Combourg/combourg.html' },
        { name: 'Commercy', url: '../../../laPosteDeLancienneFrance/Villes_C/Commercy/commercy.html' },
        { name: 'Compiegne', url: '../../../laPosteDeLancienneFrance/Villes_C/Compiegne/compiegne.html' },
        { name: 'Concarneau', url: '../../../laPosteDeLancienneFrance/Villes_C/Concarneau/concarneau.html' },
        { name: 'Conches', url: '../../../laPosteDeLancienneFrance/Villes_C/Conches/conche.html' },
        { name: 'Conde', url: '../../../laPosteDeLancienneFrance/Villes_C/Conde/conde.html' },
        { name: 'Conde-Sur-Noireau', url: '../../../laPosteDeLancienneFrance/Villes_C/Conde-Sur-Noireau/condeSurNoireau.html' },
        { name: 'Condom', url: '../../../laPosteDeLancienneFrance/Villes_C/condom/Condom.html' },
        { name: 'Condrieux', url: '../../../laPosteDeLancienneFrance/Villes_C/Condrieux/condrieux.html' },
        { name: 'Confolens', url: '../../../laPosteDeLancienneFrance/Villes_C/Confolens/confolens.html' },
        { name: 'Connerre', url: '../../../laPosteDeLancienneFrance/Villes_C/Connerre/connerre.html' },
        { name: 'Corbeil', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbeil/corbeil.html' },
        { name: 'Corbie', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbie/corbie.html' },
        { name: 'Corbeny', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbeny/corbeny.html' },
        { name: 'Corbigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbigny/corbigny.html' },
        { name: 'Cordes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cordes/cordes.html' },
        { name: 'Cormoz', url: '../../../laPosteDeLancienneFrance/Villes_C/Cormoz/cormoz.html' },
        { name: 'Corps', url: '../../../laPosteDeLancienneFrance/Villes_C/Corps/corps.html' },
        { name: 'Corse', url: '../../../laPosteDeLancienneFrance/Villes_C/Corse/corse.html' },
        { name: 'Corte', url: '../../../laPosteDeLancienneFrance/Villes_C/Corte/corte.html' },
        { name: 'Cosne', url: '../../../laPosteDeLancienneFrance/Villes_C/Cosne/cosne.html' },
        { name: 'La-Cote-St-Andre', url: '../../../laPosteDeLancienneFrance/Villes_C/La-Cote-St-Andre/laCoteStAndre.html' },
        { name: 'Cotignac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cotignac/cotignac.html' },
        { name: 'Coubert', url: '../../../laPosteDeLancienneFrance/Villes_C/Coubert/coubert.html' },
        { name: 'Couches', url: '../../../laPosteDeLancienneFrance/Villes_C/Couches/couches.html' },
        { name: 'Couhe', url: '../../../laPosteDeLancienneFrance/Villes_C/Couhe/couhe.html' },
        { name: 'Coulanges-Sur-Yonne', url: '../../../laPosteDeLancienneFrance/Villes_C/Coulanges-Sur-Yonne/coulangesSurYonne.html' },
        { name: 'Coulommiers', url: '../../../laPosteDeLancienneFrance/Villes_C/Coulommiers/coulommiers.html' },
        { name: 'Courgivaux', url: '../../../laPosteDeLancienneFrance/Villes_C/Courgivaux/courgivaux.html' },
        { name: 'Courson', url: '../../../laPosteDeLancienneFrance/Villes_C/Courson/courson.html' },
        { name: 'Courtanvault-S-Loir', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtanvault-S-Loir/courtanvaultSLoir.html' },
        { name: 'Courtenay', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtenay/courtenay.html' },
        { name: 'Courtomer', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtomer/courtomer.html' },
        { name: 'Courtrai', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtrai/courtrai.html' },
        { name: 'Courville', url: '../../../laPosteDeLancienneFrance/Villes_C/Courville/courville.html' },
        { name: 'Coutances', url: '../../../laPosteDeLancienneFrance/Villes_C/Coutances/coutances.html' },
        { name: 'Couterne', url: '../../../laPosteDeLancienneFrance/Villes_C/Couterne/couterne.html' },
        { name: 'Coutras', url: '../../../laPosteDeLancienneFrance/Villes_C/Coutras/coutras.html' },
        { name: 'Couture', url: '../../../laPosteDeLancienneFrance/Villes_C/Couture/couture.html' },
        { name: 'Cozes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cozes/cozes.html' },
        { name: 'Craon', url: '../../../laPosteDeLancienneFrance/Villes_C/Craon/craon.html' },
        { name: 'Craponne', url: '../../../laPosteDeLancienneFrance/Villes_C/Craponne/craponne.html' },
        { name: 'Crecy-En-Brie', url: '../../../laPosteDeLancienneFrance/Villes_C/Crecy-En-Brie/crecyEnBrie.html' },
        { name: 'Creil', url: '../../../laPosteDeLancienneFrance/Villes_C/Creil/creil.html' },
        { name: 'Cremieu', url: '../../../laPosteDeLancienneFrance/Villes_C/Cremieu/cremieu.html' },
        { name: 'Crepy-En-Valois', url: '../../../laPosteDeLancienneFrance/Villes_C/Crepy-En-Valois/crepyEnValois.html' },
        { name: 'Cressensac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cressensac/crenssensac.html' },
        { name: 'Crest', url: '../../../laPosteDeLancienneFrance/Villes_C/Crest/crest.html' },
        { name: 'Crevecoeur', url: '../../../laPosteDeLancienneFrance/Villes_C/Crevecoeur/crevecoeur.html' },
        { name: 'Croissanville', url: '../../../laPosteDeLancienneFrance/Villes_C/Croissanville/croissanville.html' },
        { name: 'Crolles', url: '../../../laPosteDeLancienneFrance/Villes_C/Crolles/crolles.html' },
        { name: 'Cuers', url: '../../../laPosteDeLancienneFrance/Villes_C/Cuers/cuers.html' },
        { name: 'Cuges', url: '../../../laPosteDeLancienneFrance/Villes_C/Cuges/cuges.html' },
        { name: 'Culan', url: '../../../laPosteDeLancienneFrance/Villes_C/Culan/culan.html' },
        // Ajoutez d'autres villes ici
    ];

    // Initialisation des liens de ville
    for (var i = 0; i < cityLinks.length; i++) {
        var link = document.createElement('a');
        link.href = cityLinks[i].url;
        link.textContent = cityLinks[i].name;
        dropdownContent.appendChild(link);
    }

    input.addEventListener('input', function () {
        var filter = input.value.toLowerCase();
        var links = dropdownContent.getElementsByTagName('a');

        for (var i = 0; i < links.length; i++) {
            var city = links[i].textContent.toLowerCase();
            links[i].style.display = city.includes(filter) ? '' : 'none';
        }
    });

    dropdownContent.addEventListener('click', function (event) {
        var target = event.target;
        if (target.tagName === 'A') {
            villeLink.innerHTML = ' &emsp;&emsp;' + target.textContent + '<i class="fas fa-caret-down"></i>';
            window.location.href = target.href;
        }
    });
});