document.addEventListener('DOMContentLoaded', function () {
    var input = document.getElementById('villeInput');
    var dropdownContent = document.getElementById('dropdownContent');
    var villeLink = document.getElementById('villeLink');

    // Tableau de liens de villes
    var cityLinks = [
        { name: 'Machecoul', url: '../../../laPosteDeLancienneFrance/Villes_M/Machecoul/machecoul.html' },
        { name: 'Macon', url: '../../../laPosteDeLancienneFrance/Villes_M/Macon/macon.html' },
        { name: 'Magnac', url: '../../../laPosteDeLancienneFrance/Villes_M/Magnac/magnac.html' },
        { name: 'Magny En Vexin', url: '../../../laPosteDeLancienneFrance/Villes_M/MagnyEnVexin/magnyEnVexin.html' },
        { name: 'Magny Guiscard', url: '../../../laPosteDeLancienneFrance/Villes_M/MagnyGuiscard/magnyGuiscard.html' },
        { name: 'MaillyLeChateau', url: '../../../laPosteDeLancienneFrance/Villes_M/MaillyLeChateau/maillyLeChateau.html' },
        { name: 'Maintenon', url: '../../../laPosteDeLancienneFrance/Villes_M/Maintenon/maintenon.html' },
        { name: 'MaisonNeuve', url: '../../../laPosteDeLancienneFrance/Villes_M/MaisonNeuve/maisonNeuve.html' },
        { name: 'Malesherbes', url: '../../../laPosteDeLancienneFrance/Villes_M/MalesheMalestroitrbes/malesherbes.html' },
        { name: 'Malestroit', url: '../../../laPosteDeLancienneFrance/Villes_M/malestroit/malestroit.html' },
        { name: 'Malicorne', url: '../../../laPosteDeLancienneFrance/Villes_M/Malicorne/malicorne.html' },
        { name: 'Mallemort', url: '../../../laPosteDeLancienneFrance/Villes_M/Mallemort/mallemort.html' },
        { name: 'Mamers', url: '../../../laPosteDeLancienneFrance/Villes_M/Mamers/mamers.html' },
        { name: 'Manosque', url: '../../../laPosteDeLancienneFrance/Villes_M/Manosque/manosque.html' },
        { name: 'Mans', url: '../../../laPosteDeLancienneFrance/Villes_M/Mans/lemans.html' },
        { name: 'Mansle', url: '../../../laPosteDeLancienneFrance/Villes_M/Mansle/mansle.html' },
        { name: 'Mantes', url: '../../../laPosteDeLancienneFrance/Villes_M/Mantes/mantes.html' },
        { name: 'Manthelan', url: '../../../laPosteDeLancienneFrance/Villes_M/Manthelan/manthelan.html' },
        { name: 'Marans', url: '../../../laPosteDeLancienneFrance/Villes_M/Marans/marans.html' },
        { name: 'Marchiennes', url: '../../../laPosteDeLancienneFrance/Villes_M/Marchiennes/marchiennes.html' },
        { name: 'Marcigny', url: '../../../laPosteDeLancienneFrance/Villes_M/Marcigny/marcigny.html' },
        { name: 'Marcigny-En-Auxois', url: '../../../laPosteDeLancienneFrance/Villes_M/Marcigny-En-Auxois/marcignyEnAuxois.html' },
        { name: 'Marcolsheim', url: '../../../laPosteDeLancienneFrance/Villes_M/Marcolsheim/marcolsheim.html' },
        { name: 'Marennes', url: '../../../laPosteDeLancienneFrance/Villes_M/Marennes/marennes.html' },
        { name: 'Mareuil', url: '../../../laPosteDeLancienneFrance/Villes_M/Mareuil/mareuil.html' },
        { name: 'Mariembourg', url: '../../../laPosteDeLancienneFrance/Villes_M/Mariembourg/mariembourg.html' },
        { name: 'Marigny', url: '../../../laPosteDeLancienneFrance/Villes_M/Marigny/marigny.html' },
        { name: 'Marines', url: '../../../laPosteDeLancienneFrance/Villes_M/Marines/marines.html' },
        { name: 'Maringues', url: '../../../laPosteDeLancienneFrance/Villes_M/Maringues/maringues.html' },
        { name: 'Marle', url: '../../../laPosteDeLancienneFrance/Villes_M/Marle/marle.html' },
        { name: 'Marly', url: '../../../laPosteDeLancienneFrance/Villes_M/Marly/marly.html' },
        { name: 'Marmande', url: '../../../laPosteDeLancienneFrance/Villes_M/Marmande/marmande.html' },
        { name: 'Marnay', url: '../../../laPosteDeLancienneFrance/Villes_M/Marnay/marnay.html' },
        { name: 'Marquise', url: '../../../laPosteDeLancienneFrance/Villes_M/Marquise/marquise.html' },
        { name: 'Marsal', url: '../../../laPosteDeLancienneFrance/Villes_M/Marsal/marsal.html' },
        { name: 'Marseille', url: '../../../laPosteDeLancienneFrance/Villes_M/Marseille/marseille.html' },
        { name: 'Martel', url: '../../../laPosteDeLancienneFrance/Villes_M/Martel/martel.html' },
        { name: 'Martigues', url: '../../../laPosteDeLancienneFrance/Villes_M/Martigues/martigues.html' },
        { name: 'Martres', url: '../../../laPosteDeLancienneFrance/Villes_M/Martres/martres.html' },
        { name: 'Marvejols', url: '../../../laPosteDeLancienneFrance/Villes_M/Marvejols/marvejols.html' },
        { name: 'Mas Dazil', url: '../../../laPosteDeLancienneFrance/Villes_M/Mas Dazil/masDazil.html' },
        { name: 'Massiac', url: '../../../laPosteDeLancienneFrance/Villes_M/Massiac/massiac.html' },
        { name: 'Massoulie', url: '../../../laPosteDeLancienneFrance/Villes_M/Massoulie/massoulie.html' },
        { name: 'Matignon', url: '../../../laPosteDeLancienneFrance/Villes_M/Matignon/matignon.html' },
        { name: 'Matour', url: '../../../laPosteDeLancienneFrance/Villes_M/Matour/matour.html' },
        { name: 'Maubeuge', url: '../../../laPosteDeLancienneFrance/Villes_M/Maubeuge/maubeuge.html' },
        { name: 'Maule', url: '../../../laPosteDeLancienneFrance/Villes_M/Maule/maule.html' },
        { name: 'Mauleon', url: '../../../laPosteDeLancienneFrance/Villes_M/Mauleon/Mauleon.html' },
        { name: 'Maupertuis', url: '../../../laPosteDeLancienneFrance/Villes_M/Maupertuis/maupertuis.html' },
        { name: 'Mauriac', url: '../../../laPosteDeLancienneFrance/Villes_M/Mauriac/mauriac.html' },
        { name: 'Maurs', url: '../../../laPosteDeLancienneFrance/Villes_M/Maurs/maurs.html' },
        { name: 'Mauze', url: '../../../laPosteDeLancienneFrance/Villes_M/Mauze/mauze.html' },
        { name: 'MayEnMultien', url: '../../../laPosteDeLancienneFrance/Villes_M/MayEnMultien/mayEnMultien.html' },
        { name: 'Mayenne', url: '../../../laPosteDeLancienneFrance/Villes_M/Mayenne/.html' },
        { name: 'Mayenne', url: '../../../laPosteDeLancienneFrance/Villes_M/Mayenne/mayenne.html' },
        { name: 'Mazamet', url: '../../../laPosteDeLancienneFrance/Villes_M/Mazamet/mazamet.html' },
        { name: 'Mazarin', url: '../../../laPosteDeLancienneFrance/Villes_M/Mazarin/mazarin.html' },
        { name: 'Mazeres', url: '../../../laPosteDeLancienneFrance/Villes_M/Mazeres/mazeres.html' },
        { name: 'Meaux', url: '../../../laPosteDeLancienneFrance/Villes_M/Meaux/meaux.html' },
        { name: 'Mees', url: '../../../laPosteDeLancienneFrance/Villes_M/Mees/mees.html' },
        { name: 'MehunSurYevre', url: '../../../laPosteDeLancienneFrance/Villes_M/MehunSurYevre/mehunSurYevre.html' },
        { name: 'Meilleraye', url: '../../../laPosteDeLancienneFrance/Villes_M/Meilleraye/meilleraye.html' },
        { name: 'Melle', url: '../../../laPosteDeLancienneFrance/Villes_M/Melle/melle.html' },
        { name: 'Melun', url: '../../../laPosteDeLancienneFrance/Villes_M/Melun/melun.html' },
        { name: 'MenarsLeChateau', url: '../../../laPosteDeLancienneFrance/Villes_M/MenarsLeChateau/menarsLeChateau.html' },
        { name: 'Mende', url: '../../../laPosteDeLancienneFrance/Villes_M/Mende/mende.html' },
        { name: 'Menin', url: '../../../laPosteDeLancienneFrance/Villes_M/Menin/menin.html' },
        { name: 'Mens', url: '../../../laPosteDeLancienneFrance/Villes_M/Mens/mens.html' },
        { name: 'Mer', url: '../../../laPosteDeLancienneFrance/Villes_M/Mer/mer.html' },
        { name: 'Merlerault', url: '../../../laPosteDeLancienneFrance/Villes_M/Merlerault/merlerault.html' },
        { name: 'Meru', url: '../../../laPosteDeLancienneFrance/Villes_M/Meru/meru.html' },
        { name: 'Merville', url: '../../../laPosteDeLancienneFrance/Villes_M/Merville/merville.html' },
        { name: 'MerySurSeine', url: '../../../laPosteDeLancienneFrance/Villes_M/MerySurSeine/merySurSeine.html' },
        { name: 'MesleSurSarthe', url: '../../../laPosteDeLancienneFrance/Villes_M/MesleSurSarthe/mesleSurSarthe.html' },
        { name: 'Metz', url: '../../../laPosteDeLancienneFrance/Villes_M/Metz/metz.html' },
        { name: 'Meudon', url: '../../../laPosteDeLancienneFrance/Villes_M/Meudon/meudon.html' },
        { name: 'Meulan', url: '../../../laPosteDeLancienneFrance/Villes_M/Meulan/meulan.html' },
        { name: 'MeungSurLoire', url: '../../../laPosteDeLancienneFrance/Villes_M/MeungSurLoire/meungSurLoire.html' },
        { name: 'Meximieux', url: '../../../laPosteDeLancienneFrance/Villes_M/Meximieux/meximieux.html' },
        { name: 'Meze', url: '../../../laPosteDeLancienneFrance/Villes_M/Meze/meze.html' },
        { name: 'Mezieres', url: '../../../laPosteDeLancienneFrance/Villes_M/Mezieres/mezieres.html' },
        { name: 'Mielan', url: '../../../laPosteDeLancienneFrance/Villes_M/Mielan/mielan.html' },
        { name: 'Millars', url: '../../../laPosteDeLancienneFrance/Villes_M/Millars/millars.html' },
        { name: 'Millas', url: '../../../laPosteDeLancienneFrance/Villes_M/Millas/millas.html' },
        { name: 'Millau', url: '../../../laPosteDeLancienneFrance/Villes_M/Millau/millau.html' },
        { name: 'Milly', url: '../../../laPosteDeLancienneFrance/Villes_M/Milly/milly.html' },
        { name: 'Mirambeau', url: '../../../laPosteDeLancienneFrance/Villes_M/Mirambeau/mirambeau.html' },
        { name: 'Mirande', url: '../../../laPosteDeLancienneFrance/Villes_M/Mirande/mirande.html' },
        { name: 'MirebeauEnBourgogne', url: '../../../laPosteDeLancienneFrance/Villes_M/MirebeauEnBourgogne/mirebeauEnBourgogne.html' },
        { name: 'MirebeauEnPoitou', url: '../../../laPosteDeLancienneFrance/Villes_M/MirebeauEnPoitou/miribeauEnPoitou.html' },
        { name: 'Mirecourt', url: '../../../laPosteDeLancienneFrance/Villes_M/Mirecourt/mirecourt.html' },
        { name: 'Mirepoix', url: '../../../laPosteDeLancienneFrance/Villes_M/Mirepoix/mirepoix.html' },
        { name: 'Miribel', url: '../../../laPosteDeLancienneFrance/Villes_M/Miribel/miribel.html' },
        { name: 'Moirans', url: '../../../laPosteDeLancienneFrance/Villes_M/Moirans/moirans.html' },
        { name: 'Moissac', url: '../../../laPosteDeLancienneFrance/Villes_M/Moissac/moissac.html' },
        { name: 'Molsheim', url: '../../../laPosteDeLancienneFrance/Villes_M/Molsheim/molsheim.html' },
        { name: 'Monceaux', url: '../../../laPosteDeLancienneFrance/Villes_M/Monceaux/monceaux.html' },
        { name: 'Moncontour', url: '../../../laPosteDeLancienneFrance/Villes_M/Moncontour/moncontour.html' },
        { name: 'Mondoubleau', url: '../../../laPosteDeLancienneFrance/Villes_M/Mondoubleau/mondoubleau.html' },
        { name: 'MonestierDeClermont', url: '../../../laPosteDeLancienneFrance/Villes_M/MonestierDeClermont/monestierDeClermont.html' },
        { name: 'Monistrol', url: '../../../laPosteDeLancienneFrance/Villes_M/Monistrol/monistrol.html' },
        { name: 'Monnerville', url: '../../../laPosteDeLancienneFrance/Villes_M/Monnerville/monnerville.html' },
        { name: 'Monpasier', url: '../../../laPosteDeLancienneFrance/Villes_M/Monpasier/monpasier.html' },
        { name: 'Monsegur', url: '../../../laPosteDeLancienneFrance/Villes_M/Monsegur/monsegure.html' },
        { name: 'Mont-Louis', url: '../../../laPosteDeLancienneFrance/Villes_M/Mont-Louis/montLouis.html' },
        { name: 'Montaigu', url: '../../../laPosteDeLancienneFrance/Villes_M/Montaigu/montaigu.html' },
        { name: 'MontaigutEnCombraille', url: '../../../laPosteDeLancienneFrance/Villes_M/MontaigutEnCombraille/montaigutEnCombraille.html' },
        { name: 'Montargis', url: '../../../laPosteDeLancienneFrance/Villes_M/Montargis/montargis.html' },
        { name: 'Montauban', url: '../../../laPosteDeLancienneFrance/Villes_M/Montauban/montauban.html' },
        { name: 'MontaubanDeBretagne', url: '../../../laPosteDeLancienneFrance/Villes_M/MontaubanDeBretagne/montaubanDeBretagne.html' },
        { name: 'Montbard', url: '../../../laPosteDeLancienneFrance/Villes_M/Montbard/montbard.html' },
        { name: 'Montbazon', url: '../../../laPosteDeLancienneFrance/Villes_M/Montbazon/montbazon.html' },
        { name: 'Montbeilard', url: '../../../laPosteDeLancienneFrance/Villes_M/Montbeilard/Montbeilard.html' },
        { name: 'Montbrison', url: '../../../laPosteDeLancienneFrance/Villes_M/Montbrison/montbrison.html' },
        { name: 'Montbron', url: '../../../laPosteDeLancienneFrance/Villes_M/Montbron/montbron.html' },
        { name: 'MontCenis', url: '../../../laPosteDeLancienneFrance/Villes_M/MontCenis/montCenis.html' },
        { name: 'Montcornet', url: '../../../laPosteDeLancienneFrance/Villes_M/Montcornet/montcornet.html' },
        { name: 'MontDauphin', url: '../../../laPosteDeLancienneFrance/Villes_M/MontDauphin/montDauphin.html' },
        { name: 'MontDeMarsan', url: '../../../laPosteDeLancienneFrance/Villes_M/MontDeMarsan/montDeMarsan.html' },
        { name: 'Montdidier', url: '../../../laPosteDeLancienneFrance/Villes_M/Montdidier/montdidier.html' },
        { name: 'Montebourg', url: '../../../laPosteDeLancienneFrance/Villes_M/Montebourg/montebourg.html' },
        { name: 'Montelimar', url: '../../../laPosteDeLancienneFrance/Villes_M/Montelimar/montelimar.html' },
        { name: 'Montendre', url: '../../../laPosteDeLancienneFrance/Villes_M/Montendre/montendre.html' },
        { name: 'Montereau', url: '../../../laPosteDeLancienneFrance/Villes_M/Montereau/montereau.html' },
        { name: 'MontetauxMoines', url: '../../../laPosteDeLancienneFrance/Villes_M/MontetauxMoines/montetAuxMoines.html' },
        { name: 'Montfaucon', url: '../../../laPosteDeLancienneFrance/Villes_M/Montfaucon/montfaucon.html' },
        { name: 'Montfort-LAmaury', url: '../../../laPosteDeLancienneFrance/Villes_M/Montfort-LAmaury/monfortLamaury.html' },
        { name: 'Montfrin', url: '../../../laPosteDeLancienneFrance/Villes_M/Montfrin/montfrin.html' },
        { name: 'Montgiscard', url: '../../../laPosteDeLancienneFrance/Villes_M/Montgiscard/montgiscard.html' },
        { name: 'Montierender', url: '../../../laPosteDeLancienneFrance/Villes_M/Montierender/monterender.html' },
        { name: 'Montignac', url: '../../../laPosteDeLancienneFrance/Villes_M/Montignac/montignac.html' },
        { name: 'MontignyLeRoi', url: '../../../laPosteDeLancienneFrance/Villes_M/MontignyLeRoi/montignyLeRoi.html' },
        { name: 'Montirat', url: '../../../laPosteDeLancienneFrance/Villes_M/Montirat/montirat.html' },
        { name: 'Montivilliers', url: '../../../laPosteDeLancienneFrance/Villes_M/Montivilliers/montvilliers.html' },
        { name: 'Montlhery', url: '../../../laPosteDeLancienneFrance/Villes_M/Montlhery/montlhery.html' },
        { name: 'Montlieu', url: '../../../laPosteDeLancienneFrance/Villes_M/Montlieu/montlieu.html' },
        { name: 'Montlucon', url: '../../../laPosteDeLancienneFrance/Villes_M/Montlucon/montlucon.html' },
        { name: 'Montluel', url: '../../../laPosteDeLancienneFrance/Villes_M/Montluel/montluel.html' },
        { name: 'Montmarault', url: '../../../laPosteDeLancienneFrance/Villes_M/Montmarault/montmarault.html' },
        { name: 'Montmedy', url: '../../../laPosteDeLancienneFrance/Villes_M/Montmedy/montmedy.html' },
        { name: 'Montmerle', url: '../../../laPosteDeLancienneFrance/Villes_M/Montmerle/montmerle.html' },
        { name: 'Montmirail', url: '../../../laPosteDeLancienneFrance/Villes_M/Montmirail/montmirail.html' },
        { name: 'Montmorency', url: '../../../laPosteDeLancienneFrance/Villes_M/Montmorency/montmorency.html' },
        { name: 'Montmorillon', url: '../../../laPosteDeLancienneFrance/Villes_M/Montmorillon/montmorillon.html' },
        { name: 'Montmort', url: '../../../laPosteDeLancienneFrance/Villes_M/Montmort/montmort.html' },
        { name: 'Montoire', url: '../../../laPosteDeLancienneFrance/Villes_M/Montoire/montoire.html' },
        { name: 'Montpellier', url: '../../../laPosteDeLancienneFrance/Villes_M/Montpellier/montpellier.html' },
        { name: 'Montpon', url: '../../../laPosteDeLancienneFrance/Villes_M/Montpon/montpon.html' },
        { name: 'Montrejeau', url: '../../../laPosteDeLancienneFrance/Villes_M/Montrejeau/montrejeau.html' },
        { name: 'MontreuilAuxLions', url: '../../../laPosteDeLancienneFrance/Villes_M/MontreuilAuxLions/MontreuilAuxLions.html' },
        { name: 'MontreuilBellay', url: '../../../laPosteDeLancienneFrance/Villes_M/MontreuilBellay/montreuilBellay.html' },
        { name: 'MontreuilLargille', url: '../../../laPosteDeLancienneFrance/Villes_M/MontreuilLargille/montreuilLargille.html' },
        { name: 'MontreuilSurMer', url: '../../../laPosteDeLancienneFrance/Villes_M/MontreuilSurMer/montreuilSurMer.html' },
        { name: 'Montrevault', url: '../../../laPosteDeLancienneFrance/Villes_M/Montrevault/montrevault.html' },
        { name: 'Montrichard', url: '../../../laPosteDeLancienneFrance/Villes_M/Montrichard/montrichard.html' },
        { name: 'MontSainMichel', url: '../../../laPosteDeLancienneFrance/Villes_M/MontSainMichel/montSaintMichel.html' },
        { name: 'Montsoreau', url: '../../../laPosteDeLancienneFrance/Villes_M/Montsoreau/montsoreau.html' },
        { name: 'Morand', url: '../../../laPosteDeLancienneFrance/Villes_M/Morand/morand.html' },
        { name: 'Moret', url: '../../../laPosteDeLancienneFrance/Villes_M/Moret/moret.html' },
        { name: 'Morez', url: '../../../laPosteDeLancienneFrance/Villes_M/Morez/morez.html' },
        { name: 'Morlaix', url: '../../../laPosteDeLancienneFrance/Villes_M/Morlaix/morlaix.html' },
        { name: 'Mormant', url: '../../../laPosteDeLancienneFrance/Villes_M/Mormant/mormant.html' },
        { name: 'MortagneEnPoitou', url: '../../../laPosteDeLancienneFrance/Villes_M/MortagneEnPoitou/mortagneEnPoitou.html' },
        { name: 'MortagneSurGironde', url: '../../../laPosteDeLancienneFrance/Villes_M/MortagneSurGironde/mortagneEnGironde.html' },
        { name: 'MortagneSurPerche', url: '../../../laPosteDeLancienneFrance/Villes_M/MortagneSurPerche/mortagneSurPerche.html' },
        { name: 'Mortain', url: '../../../laPosteDeLancienneFrance/Villes_M/Mortain/mortain.html' },
        { name: 'Mortefontaine', url: '../../../laPosteDeLancienneFrance/Villes_M/Mortefontaine/mortfontaine.html' },
        { name: 'Morterolles', url: '../../../laPosteDeLancienneFrance/Villes_M/Morterolles/morterolles.html' },
        { name: 'Mortree', url: '../../../laPosteDeLancienneFrance/Villes_M/Mortree/mortree.html' },
        { name: 'MotheAchard', url: '../../../laPosteDeLancienneFrance/Villes_M/MotheAchard/motheAchard.html' },
        { name: 'MotheSainHeraye', url: '../../../laPosteDeLancienneFrance/Villes_M/MotheSainHeraye/motheSaintHeraye.html' },
        { name: 'MotteSaintJean', url: '../../../laPosteDeLancienneFrance/Villes_M/MotteSaintJean/motteSaintJean.html' },
        { name: 'MoulinEngilbert', url: '../../../laPosteDeLancienneFrance/Villes_M/MoulinEngilbert/moulinEngilbert.html' },
        { name: 'Moulines', url: '../../../laPosteDeLancienneFrance/Villes_M/Moulines/moulines.html' },
        { name: 'MoulinLaMarche', url: '../../../laPosteDeLancienneFrance/Villes_M/MoulinLaMarche/moulinLaMarche.html' },
        { name: 'Moulins', url: '../../../laPosteDeLancienneFrance/Villes_M/Moulins/moulins.html' },
        { name: 'Mouzon', url: '../../../laPosteDeLancienneFrance/Villes_M/Mouzon/mouzon.html' },
        { name: 'Moyenvic', url: '../../../laPosteDeLancienneFrance/Villes_M/Moyenvic/moyenvic.html' },
        { name: 'Muide', url: '../../../laPosteDeLancienneFrance/Villes_M/Muide/muide.html' },
        { name: 'Murat', url: '../../../laPosteDeLancienneFrance/Villes_M/Murat/murat.html' },
        { name: 'MurDeBarrez', url: '../../../laPosteDeLancienneFrance/Villes_M/MurDeBarrez/murDeBarrez.html' },
        { name: 'Mure', url: '../../../laPosteDeLancienneFrance/Villes_M/Mure/mure.html' },
        { name: 'Muret', url: '../../../laPosteDeLancienneFrance/Villes_M/Muret/muret.html' },
        { name: 'Mussidan', url: '../../../laPosteDeLancienneFrance/Villes_M/Mussidan/mussidan.html' },
        { name: 'MussylEveque', url: '../../../laPosteDeLancienneFrance/Villes_M/MussylEveque/mussyLeveque.html' },
        { name: 'Muzillac', url: '../../../laPosteDeLancienneFrance/Villes_M/Muzillac/muzillac.html' },
    
        // Ajoutez d'autres villes ici
    ];

    // Initialisation des liens de ville
    for (var i = 0; i < cityLinks.length; i++) {
        var link = document.createElement('a');
        link.href = cityLinks[i].url;
        link.textContent = cityLinks[i].name;
        dropdownContent.appendChild(link);
    }

    input.addEventListener('input', function () {
        var filter = input.value.toLowerCase();
        var links = dropdownContent.getElementsByTagName('a');

        for (var i = 0; i < links.length; i++) {
            var city = links[i].textContent.toLowerCase();
            links[i].style.display = city.includes(filter) ? '' : 'none';
        }
    });

    dropdownContent.addEventListener('click', function (event) {
        var target = event.target;
        if (target.tagName === 'A') {
            villeLink.innerHTML = ' &emsp;&emsp;' + target.textContent + '<i class="fas fa-caret-down"></i>';
            window.location.href = target.href;
        }
    });
});