document.addEventListener('DOMContentLoaded', function () {
    var input = document.getElementById('villeInput');
    var dropdownContent = document.getElementById('dropdownContent');
    var villeLink = document.getElementById('villeLink');

    // Tableau de liens de villes
    var cityLinks = [
        { name: 'Cadenet', url: '../../../laPosteDeLancienneFrance/Villes_C/Cadenet/cadenet.html' },
        { name: 'Cadillac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cadillac/cadillac.html' },
        { name: 'Caen', url: '../../../laPosteDeLancienneFrance/Villes_C/Caen/caen.html' },
        { name: 'Cahors', url: '../../../laPosteDeLancienneFrance/Villes_C/Cahors/cahors.html' },
        { name: 'Calais', url: '../../../laPosteDeLancienneFrance/Villes_C/Calais/calais.html' },
        { name: 'Calvi', url: '../../../laPosteDeLancienneFrance/Villes_C/Calvi/calvi.html' },
        { name: 'Cahusac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cahusac/cahusac.html' },
        { name: 'Calvisson', url: '../../../laPosteDeLancienneFrance/Villes_C/Calvisson/calvisson.html' },
        { name: 'Camaret', url: '../../../laPosteDeLancienneFrance/Villes_C/Camaret/camaret.html' },
        { name: 'Cambrai', url: '../../../laPosteDeLancienneFrance/Villes_C/Cambrai/cambrai.html' },
        { name: 'Cande', url: '../../../laPosteDeLancienneFrance/Villes_C/Cande/cande.html' },
        { name: 'Cannes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cannes/cannes.html' },
        { name: 'Cany', url: '../../../laPosteDeLancienneFrance/Villes_C/Cany/cany.html' },
        { name: 'Caraman', url: '../../../laPosteDeLancienneFrance/Villes_C/Caraman/caraman.html' },
        { name: 'Carcassonne', url: '../../../laPosteDeLancienneFrance/Villes_C/Carcassonne/carcassonne.html' },
        { name: 'Carentan', url: '../../../laPosteDeLancienneFrance/Villes_C/Carentan/carentan.html' },
        { name: 'Carhaix', url: '../../../laPosteDeLancienneFrance/Villes_C/Carhaix/carhaix.html' },
        { name: 'Carignan', url: '../../../laPosteDeLancienneFrance/Villes_C/Carignan/carignan.html' },
        { name: 'La Carla Bayle', url: '../../../laPosteDeLancienneFrance/Villes_C/CarlaBayle/carlaBayle.html' },
        { name: 'Carpentras', url: '../../../laPosteDeLancienneFrance/Villes_C/Carpentras/carpentras.html' },
        { name: 'Carrouge', url: '../../../laPosteDeLancienneFrance/Villes_C/Carrouge/carrouge.html' },
        { name: 'Carvin', url: '../../../laPosteDeLancienneFrance/Villes_C/Carvin/carvin.html' },
        { name: 'Casal', url: '../../../laPosteDeLancienneFrance/Villes_C/Casal/casal.html' },
        { name: 'Cassel', url: '../../../laPosteDeLancienneFrance/Villes_C/Cassel/cassel.html' },
        { name: 'Cassis', url: '../../../laPosteDeLancienneFrance/Villes_C/Cassis/cassis.html' },
        { name: 'Castelfranc', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelfranc/castelfranc.html' },
        { name: 'Castellane', url: '../../../laPosteDeLancienneFrance/Villes_C/Castellane/castellane.html' },
        { name: 'Castelnau de Magnoac', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelnau/castelnau.html' },
        { name: 'Castelnau de Médoc', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelnau32/castelnau32.html' },
        { name: 'Castelnau de Montratier', url: '../../../laPosteDeLancienneFrance/Villes_C/castelnau44/castelnau44.html' },
        { name: 'Castelnaudary', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelnaudary/castelnaudary.html' },
        { name: 'Castelsarrasin', url: '../../../laPosteDeLancienneFrance/Villes_C/Castelsarrasin/castelsarrasin.html' },
        { name: 'Castillon', url: '../../../laPosteDeLancienneFrance/Villes_C/Castillon/castillon.html' },
        { name: 'Castre', url: '../../../laPosteDeLancienneFrance/Villes_C/Castre/castre.html' },
        { name: 'Castre en Guyenne', url: '../../../laPosteDeLancienneFrance/Villes_C/Castre32/castresEnGuyenne.html.html' },
        { name: 'Cateau Cambrésis', url: '../../../laPosteDeLancienneFrance/Villes_C/CateauCambresis/cateauCambresis.html' },
        { name: 'Le Catelet', url: '../../../laPosteDeLancienneFrance/Villes_C/Catelet/catelet.html' },
        { name: 'Caudebec', url: '../../../laPosteDeLancienneFrance/Villes L/Caudebec/caudebec.html' },
        { name: 'Caudrot', url: '../../../laPosteDeLancienneFrance/Villes_C/Caudrot/caudrot.html' },
        { name: 'Caudry', url: '../../../laPosteDeLancienneFrance/Villes_C/Caudry/caudry.html' },
        { name: 'Caussade', url: '../../../laPosteDeLancienneFrance/Villes_C/Caussade/caussade.html' },
        { name: 'Cauterets', url: '../../../laPosteDeLancienneFrance/Villes_C/Cauterets/cauterets.html' },
        { name: 'Cavaillon', url: '../../../laPosteDeLancienneFrance/Villes_C/Cavaillon/cavaillon.html' },
        { name: 'Cavignac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cavignac/cavignac.html' },
        { name: 'Caylus', url: '../../../laPosteDeLancienneFrance/Villes_C/Caylus/caylus.html' },
        { name: 'Cazeres', url: '../../../laPosteDeLancienneFrance/Villes_C/Cazeres/cazeres.html' },
        { name: 'Cercles', url: '../../../laPosteDeLancienneFrance/Villes_C/Cercles/cercles.html' },
        { name: 'Cerdon', url: '../../../laPosteDeLancienneFrance/Villes_C/Cerdon/cerdon.html' },
        { name: 'Céret', url: '../../../laPosteDeLancienneFrance/Villes_C/Ceret/ceret.html' },
        { name: 'Cernay', url: '../../../laPosteDeLancienneFrance/Villes_C/Cernay/cernay.html' },
        { name: 'Cervione', url: '../../../laPosteDeLancienneFrance/Villes_C/Cervione/cervione.html' },
        { name: 'Cette', url: '../../../laPosteDeLancienneFrance/Villes_C/Cette/cette.html' },
        { name: 'Chabanais', url: '../../../laPosteDeLancienneFrance/Villes_C/Chabanais/chabanais.html' },
        { name: 'Chablis', url: '../../../laPosteDeLancienneFrance/Villes_C/Chablis/chablis.html' },
        { name: 'Chagny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chagny/chagny.html' },
        { name: 'La Chaise-Dieu', url: '../../../laPosteDeLancienneFrance/Villes_CChaiseDieu/chaiseDieu/.html' },
        { name: 'Chalabre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalabre/chalabre.html' },
        { name: 'Chalamont', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalamont/chalamont.html' },
        { name: 'Le Chalard', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalard/chalard.html' },
        { name: 'Chalaure', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalaure/chalaure.html' },
        { name: 'Challans', url: '../../../laPosteDeLancienneFrance/Villes_C/Challans/challans.html' },
        { name: 'Chalon-Sur-Saone', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalon-Sur-Saone/chalonSurSaone.html' },
        { name: 'Chalons-Sur-Marne', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalons-Sur-Marne/chalonsSurMarne.html' },
        { name: 'Chalus', url: '../../../laPosteDeLancienneFrance/Villes_C/Chalus/chalus.html' },
        { name: 'Chambly', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambly/chambly.html' },
        { name: 'Chambon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambon/chambon.html' },
        { name: 'Chambord', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambord/chambord.html' },
        { name: 'Chambrais', url: '../../../laPosteDeLancienneFrance/Villes_C/Chambrais/chambrais.html' },
        { name: 'Champagnole', url: '../../../laPosteDeLancienneFrance/Villes_C/Champagnole/champagnole.html' },
        { name: 'Champigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Champigny/champigny.html' },
        { name: 'Champlitte', url: '../../../laPosteDeLancienneFrance/Villes_C/Champlitte/champlitte.html' },
        { name: 'Champrond', url: '../../../laPosteDeLancienneFrance/Villes_C/Champrond/champrond.html' },
        { name: 'Chanceaux', url: '../../../laPosteDeLancienneFrance/Villes_C/Chanceaux/chanceaux.html' },
        { name: 'Chanteloube', url: '../../../laPosteDeLancienneFrance/Villes_C/Chanteloube/chanteloube.html' },
        { name: 'Chantilly', url: '../../../laPosteDeLancienneFrance/Villes_C/Chantilly/chantilly.html' },
        { name: 'Chantonnay', url: '../../../laPosteDeLancienneFrance/Villes_C/Chantonnay/chantonnay.html' },
        { name: 'Chaource', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaource/chaource.html' },
        { name: 'Charente', url: '../../../laPosteDeLancienneFrance/Villes_C/Charente/charante.html' },
        { name: 'Charenton', url: '../../../laPosteDeLancienneFrance/Villes_C/Charenton/charenton.html' },
        { name: 'La Charite', url: '../../../laPosteDeLancienneFrance/Villes_C/Charite/charite.html' },
        { name: 'Charlemont', url: '../../../laPosteDeLancienneFrance/Villes_C/Charlemont/charlemont.html' },
        { name: 'Charleroi', url: '../../../laPosteDeLancienneFrance/Villes_C/Charleroi/charleroi.html' },
        { name: 'Charleville', url: '../../../laPosteDeLancienneFrance/Villes_C/Charleville/charleville.html' },
        { name: 'Charly', url: '../../../laPosteDeLancienneFrance/Villes_C/Charly/charly.html' },
        { name: 'Charmes', url: '../../../laPosteDeLancienneFrance/Villes_C/Charmes/charmes.html' },
        { name: 'Charolles', url: '../../../laPosteDeLancienneFrance/Villes_C/Charolles/charolles.html' },
        { name: 'Charost', url: '../../../laPosteDeLancienneFrance/Villes_C/Charost/charost.html' },
        { name: 'Chartre sur le Loir', url: '../../../laPosteDeLancienneFrance/Villes_C/Chartre/chartreSurLeLoir.html' },
        { name: 'Chartre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chartre27/chartres.html' },
        { name: 'Chataigneraie', url: '../../../laPosteDeLancienneFrance/Villes_CChataigneraie/chataigneraie/.html' },
        { name: 'Chateau-Chalon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau1chalon/chateauChalon.html' },
        { name: 'Chateau-Chinon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau2Chinon/chateauChinon.html' },
        { name: 'Chateau-du-Loir', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau3Loire/chateauDuLoir.html' },
        { name: 'Chateau-Gontier', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau4Gontier/chateauGontier.html' },
        { name: 'Chateau-Landon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau5Landon/chateauLandon.html' },
        { name: 'Chateau-Porcien', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau6Porcien/chateauPorcien.html' },
        { name: 'Chateau-Renault', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau7Renault/chateauRenault.html' },
        { name: 'Chateau-Salins', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau8Salins/chateauSalins.html' },
        { name: 'Chateau-Thierry', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau9Thierry/chateauThierry.html' },
        { name: 'Chateau-Villain', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateau10Villain/chateauVillain.html' },
        { name: 'Chateaubriant', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaubriant/chateaubriant.html' },
        { name: 'Chateaudun', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaudun/chateaudun.html' },
        { name: 'Chateaulin', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaulin/chateaulin.html' },
        { name: 'Chateaumeillant', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateaumeillant/chateaumeillant.html' },
        { name: 'Chateauneuf', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf1/Chateauneuf.html' },
        { name: 'Chateauneuf de Bretagne', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf2deBretagne/chateaunefDeBretagne.html' },
        { name: 'Chateauneuf sur Cher', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf3surCher/chateaneufSurCher.html' },
        { name: 'Chateauneuf en Thymerais', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauneuf4enThymerais/chateaunefEnThymerais.html' },
        { name: 'Chateauroux', url: '../../../laPosteDeLancienneFrance/Villes_C/Chateauroux/chateauroux.html' },
        { name: 'Chatel sur Moselle', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatel/chatelSurMoselle.html' },
        { name: 'Chatelaudren', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatelaudren/chatelaudren.html' },
        { name: 'Le chatelet en Brie', url: '../../../laPosteDeLancienneFrance/Villes_C/ChateletEnBrie/leChateletEnBrie.html' },
        { name: 'Chatellerault', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatellerault/chatellerault.html' },
        { name: 'Chatillon de Michaille', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon1deMichaille/chatillonDeMichaille.html' },
        { name: 'Chatillon les Dombes', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon2LesDombes/chatillonLesDombes.html' },
        { name: 'Chatillon sur Indre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon3SurIndre/chatillonSurIndre.html' },
        { name: 'Chatillon sur Loing', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon4SurLoing/chatillonSurLoing.html' },
        { name: 'Chatillon sur Loire', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon5SurLoire/chatillonSurLoire.html' },
        { name: 'Chatillon sur Marne', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon6SurMarne/chatillonSurMarne.html' },
        { name: 'Chatillon sur Seine', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon7SurSeine/chatillonSurSeine.html' },
        { name: 'Chatillon sur Sevre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatillon8SurSevre/chatillonSurSevre.html' },
        { name: 'Chatou', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatou/chatou.html' },
        { name: 'La Chatre', url: '../../../laPosteDeLancienneFrance/Villes_C/Chatre/laChatre.html' },
        { name: 'Chaudesaigues', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaudesaigues/chaudesaigues.html' },
        { name: 'Chaumes', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaumes/chaumes.html' },
        { name: 'Chaumont en Bassigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaumont50/chaumontEnBassigny.html' },
        { name: 'Chaumont en Vexin', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaumont58/chaumontEnVexin.html' },
        { name: 'Chaunai', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaunai/chaunai.html' },
        { name: 'Chauny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chauny/chauny.html' },
        { name: 'La Chaussee', url: '../../../laPosteDeLancienneFrance/Villes_C/Chaussee/laChaussee.html' },
        { name: 'Chauvigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Chauvigny/chauvigny.html' },
        { name: 'Chazelles', url: '../../../laPosteDeLancienneFrance/Villes_C/Chazelles/chazelles.html' },
        { name: 'Chef Boutonne', url: '../../../laPosteDeLancienneFrance/Villes_C/ChefBoutonne/chefBoutonne.html' },
        { name: 'Chelles', url: '../../../laPosteDeLancienneFrance/Villes_C/Chelles/chelles.html' },
        { name: 'Chemille', url: '../../../laPosteDeLancienneFrance/Villes_C/Chemille/chemille.html' },
        { name: 'Chenerailles', url: '../../../laPosteDeLancienneFrance/Villes_C/Chenerailles/chenerailles.html' },
        { name: 'Cherbourg', url: '../../../laPosteDeLancienneFrance/Villes_C/Cherbourg/cherbourg.html' },
        { name: 'Cheroy', url: '../../../laPosteDeLancienneFrance/Villes_C/Cheroy/cheroy.html' },
        { name: 'Chevilly', url: '../../../laPosteDeLancienneFrance/Villes_C/Chevilly/chevilly.html' },
        { name: 'Chevreuse', url: '../../../laPosteDeLancienneFrance/Villes_C/Chevreuse/chevreuse.html' },
        { name: 'Chezy', url: '../../../laPosteDeLancienneFrance/Villes_C/Chezy/chezy.html' },
        { name: 'Chilleurs', url: '../../../laPosteDeLancienneFrance/Villes_C/Chilleurs/chilleurs.html' },
        { name: 'Chinon', url: '../../../laPosteDeLancienneFrance/Villes_C/Chinon/chinon.html' },
        { name: 'Choisy le Roi', url: '../../../laPosteDeLancienneFrance/Villes_C/Choisy/choisyLeRoi.html' },
        { name: 'Cholet', url: '../../../laPosteDeLancienneFrance/Villes_C/Cholet/cholet.html' },
        { name: 'Chomerac', url: '../../../laPosteDeLancienneFrance/Villes_C/Chomerac/chomerac.html' },
        { name: 'Chorges', url: '../../../laPosteDeLancienneFrance/Villes_C/Chorges/chorges.html' },
        { name: 'Chouze', url: '../../../laPosteDeLancienneFrance/Villes_C/Chouze/chouze.html' },
        { name: 'Cingetabelle', url: '../../../laPosteDeLancienneFrance/Villes_C/Cingetabelle/cingetabelle.html' },
        { name: 'Cintrey', url: '../../../laPosteDeLancienneFrance/Villes_C/Cintrey/cintrey.html' },
        { name: 'La Ciotat', url: '../../../laPosteDeLancienneFrance/Villes_C/Ciotat/laCiotat.html' },
        { name: 'Cirey S Blaise', url: '../../../laPosteDeLancienneFrance/Villes_C/Cirey/cireySBlaise.html' },
        { name: 'Civray', url: '../../../laPosteDeLancienneFrance/Villes_C/Civray/civray.html' },
        { name: 'Cizay', url: '../../../laPosteDeLancienneFrance/Villes_C/Cizay/cizay.html' },
        { name: 'Clairac', url: '../../../laPosteDeLancienneFrance/Villes_C/Clairac/clairac.html' },
        { name: 'Clairvaux', url: '../../../laPosteDeLancienneFrance/Villes_C/Clairvaux/clairvaux.html' },
        { name: 'Clamecy', url: '../../../laPosteDeLancienneFrance/Villes_C/Clamecy/clamecy.html' },
        { name: 'Claye', url: '../../../laPosteDeLancienneFrance/Villes_C/Claye/Claye.html' },
        { name: 'La Clayette', url: '../../../laPosteDeLancienneFrance/Villes_C/Clayette/laClayette.html' },
        { name: 'Clermont en Argonne', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont1/clermontEnArgonne.html' },
        { name: 'Clermont en Beauvoisis', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont2/clermontEnBeauvoisis.html' },
        { name: 'Clermont Ferrand', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont3/clermontFerrand.html' },
        { name: 'Clermont Lodeve', url: '../../../laPosteDeLancienneFrance/Villes_C/Clermont4/clermontLodeve.html' },
        { name: 'Clerval', url: '../../../laPosteDeLancienneFrance/Villes_C/Clerval/clerval.html' },
        { name: 'Clery', url: '../../../laPosteDeLancienneFrance/Villes_C/Clery/clery.html' },
        { name: 'Clisson', url: '../../../laPosteDeLancienneFrance/Villes_C/Clisson/clisson.html' },
        { name: 'Cloyes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cloyes/cloyes.html' },
        { name: 'Cluny', url: '../../../laPosteDeLancienneFrance/Villes_C/Cluny/cluny.html' },
        { name: 'Cocherel', url: '../../../laPosteDeLancienneFrance/Villes_C/Cocherel/cocherel.html' },
        { name: 'Cognac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cognac/cognac.html' },
        { name: 'Coillure', url: '../../../laPosteDeLancienneFrance/Villes_C/Coillure/coillure.html' },
        { name: 'Coincy', url: '../../../laPosteDeLancienneFrance/Villes_C/Coincy/coincy.html' },
        { name: 'Collobrieres', url: '../../../laPosteDeLancienneFrance/Villes_C/Collobrieres/collobrieres.html' },
        { name: 'Collonges', url: '../../../laPosteDeLancienneFrance/Villes_C/Collonges/collonges.html' },
        { name: 'Colmar', url: '../../../laPosteDeLancienneFrance/Villes_C/Colmar/colmar.html' },
        { name: 'Colmars', url: '../../../laPosteDeLancienneFrance/Villes_C/Colmars/colmars.html' },
        { name: 'Colombey', url: '../../../laPosteDeLancienneFrance/Villes_C/Colombey/colombey.html' },
        { name: 'Combouin', url: '../../../laPosteDeLancienneFrance/Villes_C/Combouin/combouin.html' },
        { name: 'Combourg', url: '../../../laPosteDeLancienneFrance/Villes_C/Combourg/combourg.html' },
        { name: 'Commercy', url: '../../../laPosteDeLancienneFrance/Villes_C/Commercy/commercy.html' },
        { name: 'Compiegne', url: '../../../laPosteDeLancienneFrance/Villes_C/Compiegne/compiegne.html' },
        { name: 'Concarneau', url: '../../../laPosteDeLancienneFrance/Villes_C/Concarneau/concarneau.html' },
        { name: 'Conches', url: '../../../laPosteDeLancienneFrance/Villes_C/Conches/conches.html' },
        { name: 'Conde', url: '../../../laPosteDeLancienneFrance/Villes_C/Conde/conde.html' },
        { name: 'Conde sur Noireau', url: '../../../laPosteDeLancienneFrance/Villes_C/Conde13/condeSurNoireau.html' },
        { name: 'Condom', url: '../../../laPosteDeLancienneFrance/Villes_C/condom/Condom.html' },
        { name: 'Condrieux', url: '../../../laPosteDeLancienneFrance/Villes_C/Condrieux/condrieux.html' },
        { name: 'Confolens', url: '../../../laPosteDeLancienneFrance/Villes_C/Confolens/confolens.html' },
        { name: 'Connerre', url: '../../../laPosteDeLancienneFrance/Villes_C/Connerre/connerre.html' },
        { name: 'Corbeil', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbeil/corbeil.html' },
        { name: 'Corbie', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbie/corbie.html' },
        { name: 'Corbeny', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbeny/corbeny.html' },
        { name: 'Corbigny', url: '../../../laPosteDeLancienneFrance/Villes_C/Corbigny/corbigny.html' },
        { name: 'Cordes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cordes/cordes.html' },
        { name: 'Cormoz', url: '../../../laPosteDeLancienneFrance/Villes_C/Cormoz/cormoz.html' },
        { name: 'Corps', url: '../../../laPosteDeLancienneFrance/Villes_C/Corps/corps.html' },
        { name: 'Corse', url: '../../../laPosteDeLancienneFrance/Villes_C/Corse/corse.html' },
        { name: 'Corte', url: '../../../laPosteDeLancienneFrance/Villes_C/Corte/Ccorte.html' },
        { name: 'Cosne', url: '../../../laPosteDeLancienneFrance/Villes_C/Cosne/cosne.html' },
        { name: 'La Cote St Andre', url: '../../../laPosteDeLancienneFrance/Villes_C/CoteStAndre/coteStAndre.html' },
        { name: 'Cotignac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cotignac/cotignac.html' },
        { name: 'Coubert', url: '../../../laPosteDeLancienneFrance/Villes_C/Coubert/coubert.html' },
        { name: 'Couches', url: '../../../laPosteDeLancienneFrance/Villes_C/Couches/couches.html' },
        { name: 'Couhe', url: '../../../laPosteDeLancienneFrance/Villes_C/Couhe/couhe.html' },
        { name: 'Coulanges sur Yonne', url: '../../../laPosteDeLancienneFrance/Villes_C/Coulanges/coulangesSurYonne.html' },
        { name: 'Coullomiers', url: '../../../laPosteDeLancienneFrance/Villes_C/Coullomiers/coullomiers.html' },
        { name: 'Courgivaux', url: '../../../laPosteDeLancienneFrance/Villes_C/Courgivaux/courgivaux.html' },
        { name: 'Courson', url: '../../../laPosteDeLancienneFrance/Villes_C/Courson/courson.html' },
        { name: 'Courtanvault S Loir', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtanvault/courtanvaultSurLoir.html' },
        { name: 'Courtenay', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtenay/courtenay.html' },
        { name: 'Courtomer', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtomer/courtomer.html' },
        { name: 'Courtrai', url: '../../../laPosteDeLancienneFrance/Villes_C/Courtrai/courtrai.html' },
        { name: 'Courville', url: '../../../laPosteDeLancienneFrance/Villes_C/Courville/courville.html' },
        { name: 'Coutances', url: '../../../laPosteDeLancienneFrance/Villes_C/Coutances/coutances.html' },
        { name: 'Couterne', url: '../../../laPosteDeLancienneFrance/Villes_C/Couterne/couterne.html' },
        { name: 'Coutras', url: '../../../laPosteDeLancienneFrance/Villes_C/Coutras/coutras.html' },
        { name: 'Couture', url: '../../../laPosteDeLancienneFrance/Villes_C/Couture/couture.html' },
        { name: 'Cozes', url: '../../../laPosteDeLancienneFrance/Villes_C/Cozes/cozes.html' },
        { name: 'Craon', url: '../../../laPosteDeLancienneFrance/Villes_C/Craon/craon.html' },
        { name: 'Craponne', url: '../../../laPosteDeLancienneFrance/Villes_C/Craponne/craponne.html' },
        { name: 'Crecy En Brie', url: '../../../laPosteDeLancienneFrance/Villes_C/CrecyEnBrie/crecyEnBrie.html' },
        { name: 'Creil', url: '../../../laPosteDeLancienneFrance/Villes_C/Creil/creil.html' },
        { name: 'Cremieu', url: '../../../laPosteDeLancienneFrance/Villes_C/Cremieu/cremieu.html' },
        { name: 'Crepy en Valois', url: '../../../laPosteDeLancienneFrance/Villes_C/Crepy/crepyEnValois.html' },
        { name: 'Cressensac', url: '../../../laPosteDeLancienneFrance/Villes_C/Cressensac/crenssensac.html' },
        { name: 'Crest', url: '../../../laPosteDeLancienneFrance/Villes_C/Crest/crest.html' },
        { name: 'Crevecoeur', url: '../../../laPosteDeLancienneFrance/Villes_C/Crevecoeur/crevecoeur.html' },
        { name: 'Croissanville', url: '../../../laPosteDeLancienneFrance/Villes_C/Croissanville/croissanville.html' },
        { name: 'Crolles', url: '../../../laPosteDeLancienneFrance/Villes_C/Crolles/crolles.html' },
        { name: 'Cuers', url: '../../../laPosteDeLancienneFrance/Villes_C/Cuers/cuers.html' },
        { name: 'Cuges', url: '../../../laPosteDeLancienneFrance/Villes_C/Cuges/cuges.html' },
        { name: 'Culan', url: '../../../laPosteDeLancienneFrance/Villes_C/Culan/culan.html' },
        // Ajoutez d'autres villes ici
    ];

    // Initialisation des liens de ville
    for (var i = 0; i < cityLinks.length; i++) {
        var link = document.createElement('a');
        link.href = cityLinks[i].url;
        link.textContent = cityLinks[i].name;
        dropdownContent.appendChild(link);
    }

    input.addEventListener('input', function () {
        var filter = input.value.toLowerCase();
        var links = dropdownContent.getElementsByTagName('a');

        for (var i = 0; i < links.length; i++) {
            var city = links[i].textContent.toLowerCase();
            links[i].style.display = city.includes(filter) ? '' : 'none';
        }
    });

    dropdownContent.addEventListener('click', function (event) {
        var target = event.target;
        if (target.tagName === 'A') {
            villeLink.innerHTML = ' &emsp;&emsp;' + target.textContent + '<i class="fas fa-caret-down"></i>';
            window.location.href = target.href;
        }
    });
});