document.addEventListener('DOMContentLoaded', function () {
    var input = document.getElementById('villeInput');
    var dropdownContent = document.getElementById('dropdownContent');
    var villeLink = document.getElementById('villeLink');

    // Tableau de liens de villes
    var cityLinks = [
        { name: 'Baccarat',  url: '../../../laPosteDeLancienneFrance/Villes B/Baccarat/baccarat.html' },
        { name: 'Bagneres_De_Bigorre', url: '../../../laPosteDeLancienneFrance/Villes B/Bagneres_De_Bigorre/BagneresDeBigorre.html' },
        { name: 'Bagneres_De_Louchon', url: '../../../laPosteDeLancienneFrance/Villes B/Bagneres_De_Louchon/bagneresDeLouchon.html' },
        { name: 'Bagnols', url: '../../../laPosteDeLancienneFrance/Villes B/Bagnols/bagnols.html' },
        { name: 'Bailleul', url: '../../../laPosteDeLancienneFrance/Villes B/Bailleul/bailleul.html' },
        { name: 'Bain', url: '../../../laPosteDeLancienneFrance/Villes B/Bain/bain.html' },
        { name: 'Bains', url: '../../../laPosteDeLancienneFrance/Villes B/Bains/bains.html' },
        { name: 'Baisieux', url: '../../../laPosteDeLancienneFrance/Villes B/Baisieux/baisieux.html' },
        { name: 'Balleroy', url: '../../../laPosteDeLancienneFrance/Villes B/Balleroy/balleroy.html' },
        { name: 'Bapaume', url: '../../../laPosteDeLancienneFrance/Villes B/Bapaume/bapaume.html' },
        { name: 'Bar le Duc', url: '../../../laPosteDeLancienneFrance/Villes B/BarLeDuc/barLeDuc.html' },
        { name: 'Bar sur Aube', url: '../../../laPosteDeLancienneFrance/Villes B/BarSurAube/barSurAube.html' },
        { name: 'Bar sur Seine', url: '../../../laPosteDeLancienneFrance/Villes B/BarSurSeine/barSurSeine.html' },
        { name: 'La Baraque sous Gevrey', url: '../../../laPosteDeLancienneFrance/Villes B/baraque/Baraque.html' },
        { name: 'Barbencon', url: '../../../laPosteDeLancienneFrance/Villes B/Barbencon/barbencon.html' },
        { name: 'Barbentane', url: '../../../laPosteDeLancienneFrance/Villes B/Barbentane/barbentane.html' },
        { name: 'Barbezieux', url: '../../../laPosteDeLancienneFrance/Villes B/Barbezieux/barbezieux.html' },
        { name: 'Barbonne', url: '../../../laPosteDeLancienneFrance/Villes B/Barbonne/barbonne.html' },
        { name: 'Barcelonnette', url: '../../../laPosteDeLancienneFrance/Villes B/Barcelonnette/barcelonette.html' },
        { name: 'Bareges', url: '../../../laPosteDeLancienneFrance/Villes B/Bareges/bareges.html' },
        { name: 'Barentin', url: '../../../laPosteDeLancienneFrance/Villes B/Barentin/barentin.html' },
        { name: 'Barjac', url: '../../../laPosteDeLancienneFrance/Villes B/Barjac/barjac.html' },
        { name: 'Barjols', url: '../../../laPosteDeLancienneFrance/Villes B/Barjols/barjols.html' },
        { name: 'Barraux', url: '../../../laPosteDeLancienneFrance/Villes B/Barraux/barraux.html' },
        { name: 'La Barre', url: '../../../laPosteDeLancienneFrance/Villes B/Barre/barre.html' },
        { name: 'Basses', url: '../../../laPosteDeLancienneFrance/Villes B/Basses/bassee.html' },
        { name: 'Bassou', url: '../../../laPosteDeLancienneFrance/Villes B/Bassou/bassou.html' },
        { name: 'Bastia', url: '../../../laPosteDeLancienneFrance/Villes B/Bastia/bastia.html' },
        { name: 'Bauge', url: '../../../laPosteDeLancienneFrance/Villes B/Bauge/bauge.html' },
        { name: 'Baume les Dames', url: '../../../laPosteDeLancienneFrance/Villes B/Baume/baume.html' },
        { name: 'Bavay', url: '../../../laPosteDeLancienneFrance/Villes B/Bavay/bavay.html' },
        { name: 'Bayeux', url: '../../../laPosteDeLancienneFrance/Villes B/Bayeux/bayeux.html' },
        { name: 'Bayonne', url: '../../../laPosteDeLancienneFrance/Villes B/Bayonne/bayonne.html' },
        { name: 'Bazas', url: '../../../laPosteDeLancienneFrance/Villes B/Bazas/bazas.html' },
        { name: 'Beaucaire', url: '../../../laPosteDeLancienneFrance/Villes B/Beaucaire/beaucaire.html' },
        { name: 'Beaufort', url: '../../../laPosteDeLancienneFrance/Villes B/Beaufort/beaufort.html' },
        { name: 'Beaugency', url: '../../../laPosteDeLancienneFrance/Villes B/Beaugency/beaugency.html' },
        { name: 'Beaujeu', url: '../../../laPosteDeLancienneFrance/Villes B/Beaujeu/beaujeu.html' },
        { name: 'Beaulieu (36)', url: '../../../laPosteDeLancienneFrance/Villes B/Beaulieu36/beaulieu36.html' },
        { name: 'Beaulieu (18)', url: '../../../laPosteDeLancienneFrance/Villes B/Beaulieu18/beaulieu18.html' },
        { name: 'Beaulieu79', url: '../../../laPosteDeLancienneFrance/Villes B/Beaulieu79/beaulieu79.html' },
        { name: 'BeaumontDeLomagne', url: '../../../laPosteDeLancienneFrance/Villes B/BeaumontDeLomagne/beaumontDeLomagne.html' },
        { name: 'BeaumontLeRoger', url: '../../../laPosteDeLancienneFrance/Villes B/BeaumontLeRoger/beaumontLeRoger.html' },
        { name: 'BeaumontLeVicomte', url: '../../../laPosteDeLancienneFrance/Villes B/BeaumontLeVicomte/beaumontLeVicomte.html' },
        { name: 'BeaumontSurOise', url: '../../../laPosteDeLancienneFrance/Villes B/BeaumontSurOise/beaumontSurOise.html' },
        { name: 'Beaune', url: '../../../laPosteDeLancienneFrance/Villes B/Beaune/beaune.html' },
        { name: 'Beaupreau', url: '../../../laPosteDeLancienneFrance/Villes B/Beaupreau/beaupreau.html' },
        { name: 'Beaurepaire', url: '../../../laPosteDeLancienneFrance/Villes B/Beaurepaire/beaurepaire.html' },
        { name: 'Le Beausset', url: '../../../laPosteDeLancienneFrance/Villes B/Beausset/beausset.html' },
        { name: 'Beauvais', url: '../../../laPosteDeLancienneFrance/Villes B/Beauvais/beauvais.html' },
        { name: 'Beauvoir sur mer', url: '../../../laPosteDeLancienneFrance/Villes B/Beauvoir/beauvoir.html' },
        { name: 'Becherel', url: '../../../laPosteDeLancienneFrance/Villes B/Becherel/becherel.html' },
        { name: 'Bedarieux', url: '../../../laPosteDeLancienneFrance/Villes B/Bedarieux/bedarieux.html' },
        { name: 'Belfort', url: '../../../laPosteDeLancienneFrance/Villes B/Belfort/belfort.html' },
        { name: 'Bellac', url: '../../../laPosteDeLancienneFrance/Villes B/Bellac/bellac.html' },
        { name: 'BelleIsleEnMer', url: '../../../laPosteDeLancienneFrance/Villes B/BelleIsleEnMer/belleIsleEnMer.html' },
        { name: 'Belle Isle en Terre', url: '../../../laPosteDeLancienneFrance/Villes B/BelleIsleEnTerre/belleIsleEnTerre.html' },
        { name: 'Bellegarde', url: '../../../laPosteDeLancienneFrance/Villes B/Bellegarde/bellegarde.html' },
        { name: 'Bellemare', url: '../../../laPosteDeLancienneFrance/Villes B/Bellemare/bellemare.html' },
        { name: 'Belleme', url: '../../../laPosteDeLancienneFrance/Villes B/Belleme/belleme.html' },
        { name: 'Belleville sur Saone', url: '../../../laPosteDeLancienneFrance/Villes B/Belleville/belleville.html' },
        { name: 'Belley', url: '../../../laPosteDeLancienneFrance/Villes B/Belley/belley.html' },
        { name: 'Belpech', url: '../../../laPosteDeLancienneFrance/Villes B/Belpech/belpech.html' },
        { name: 'Belves', url: '../../../laPosteDeLancienneFrance/Villes B/Belves/belves.html' },
        { name: 'Benfeld', url: '../../../laPosteDeLancienneFrance/Villes B/Benfeld/benfeld.html' },
        { name: 'Bergerac', url: '../../../laPosteDeLancienneFrance/Villes B/Bergerac/bergerac.html' },
        { name: 'Bergues', url: '../../../laPosteDeLancienneFrance/Villes B/Bergues/bergues.html' },
        { name: 'Bernay', url: '../../../laPosteDeLancienneFrance/Villes B/Bernay/bernay.html' },
        { name: 'Besancon', url: '../../../laPosteDeLancienneFrance/Villes B/Besancon/besancon.html' },
        { name: 'Besse', url: '../../../laPosteDeLancienneFrance/Villes B/Besse/besse.html' },
        { name: 'Bessines', url: '../../../laPosteDeLancienneFrance/Villes B/Bessines/bessines.html' },
        { name: 'Bethleem', url: '../../../laPosteDeLancienneFrance/Villes B/Bethleem/bethleem.html' },
        { name: 'Bethune', url: '../../../laPosteDeLancienneFrance/Villes B/Bethune/bethune.html' },
        { name: 'Bezier', url: '../../../laPosteDeLancienneFrance/Villes B/Beziers/beziers.html' },
        { name: 'Billom', url: '../../../laPosteDeLancienneFrance/Villes B/Billom/billom.html' },
        { name: 'Binche', url: '../../../laPosteDeLancienneFrance/Villes B/Binche/binche.html' },
        { name: 'Bitche', url: '../../../laPosteDeLancienneFrance/Villes B/Bitche/bitche.html' },
        { name: 'Blain', url: '../../../laPosteDeLancienneFrance/Villes B/Blain/blain.html' },
        { name: 'Blamont (24)', url: '../../../laPosteDeLancienneFrance/Villes B/Blamont24/blamont24.html' },
        { name: 'Blamont (52)', url: '../../../laPosteDeLancienneFrance/Villes B/Blamont52/blamont52.html' },
        { name: 'Le Blanc', url: '../../../laPosteDeLancienneFrance/Villes B/Blanc/blanc.html' },
        { name: 'Blanzac', url: '../../../laPosteDeLancienneFrance/Villes B/Blanzac/blanzac.html' },
        { name: 'Blaye', url: '../../../laPosteDeLancienneFrance/Villes B/Blaye/blaye.html' },
        { name: 'Bléré', url: '../../../laPosteDeLancienneFrance/Villes B/Bléré/bléré.html' },
        { name: 'Blois', url: '../../../laPosteDeLancienneFrance/Villes B/Blois/blois.html' },
        { name: 'Blosseville', url: '../../../laPosteDeLancienneFrance/Villes B/Blosseville/blosseville.html' },
        { name: 'Besançon', url: '../../../laPosteDeLancienneFrance/Villes B/Besançon/besançon.html' },
        { name: 'Boiscommun', url: '../../../laPosteDeLancienneFrance/Villes B/Boiscommun/boiscommun.html' },
        { name: 'Boissy St Leger', url: '../../../laPosteDeLancienneFrance/Villes B/Boissy/boissy.html' },
        { name: 'Bolbec', url: '../../../laPosteDeLancienneFrance/Villes B/Bolbec/bolbec.html' },
        { name: 'Le Bolhard', url: '../../../laPosteDeLancienneFrance/Villes B/Bolhard/bolhard.html' },
        { name: 'Boncourt', url: '../../../laPosteDeLancienneFrance/Villes B/Boncourt/boncourt.html' },
        { name: 'Bondy', url: '../../../laPosteDeLancienneFrance/Villes B/Bondy/bondy.html' },
        { name: 'Bonifacio', url: '../../../laPosteDeLancienneFrance/Villes B/Bonifacio/bonifacio.html' },
        { name: 'Bonnelles', url: '../../../laPosteDeLancienneFrance/Villes B/Bonnelles/bonnelles.html' },
        { name: 'Bonnetable', url: '../../../laPosteDeLancienneFrance/Villes B/Bonnetable/bonnetable.html' },
        { name: 'Bonneval', url: '../../../laPosteDeLancienneFrance/Villes B/Bonneval/bonneval.html' },
        { name: 'Bonnieres', url: '../../../laPosteDeLancienneFrance/Villes B/Bonnieres/bonnieres.html' },
        { name: 'Bonny', url: '../../../laPosteDeLancienneFrance/Villes B/Bonny/bonny.html' },
        { name: 'Le Bordeau de Vigny', url: '../../../laPosteDeLancienneFrance/Villes B/Bordeau/bordeau.html' },
        { name: 'Bordeaux', url: '../../../laPosteDeLancienneFrance/Villes B/Bordeaux/bordeaux.html' },
        { name: 'Petite poste de Bordeaux', url: '../../../laPosteDeLancienneFrance/Villes B/Bordeauxpp/bordeauxpp.html' },
        { name: 'Bort', url: '../../../laPosteDeLancienneFrance/Villes B/Bort/bort.html' },
        { name: 'Bouchain', url: '../../../laPosteDeLancienneFrance/Villes B/Bouchain/bouchain.html' },
        { name: 'Boucoiran', url: '../../../laPosteDeLancienneFrance/Villes B/Boucoiran/boucoiran.html' },
        { name: 'Bouillon', url: '../../../laPosteDeLancienneFrance/Villes B/Bouillon/bouillon.html' },
        { name: 'Boulay', url: '../../../laPosteDeLancienneFrance/Villes B/Boulay/boulay.html' },
        { name: 'Boulogne', url: '../../../laPosteDeLancienneFrance/Villes B/Boulogne/Boulogne.html' },
        { name: 'Boulogne sur Mer', url: '../../../laPosteDeLancienneFrance/Villes B/BoulogneSurMer/boulogneSurMer.html' },
        { name: 'Boulou', url: '../../../laPosteDeLancienneFrance/Villes B/Boulou/boulou.html' },
        { name: 'Bouquenon', url: '../../../laPosteDeLancienneFrance/Villes B/Bouquenon/bouquenon.html' },
        { name: 'Bourbon L Archambault', url: '../../../laPosteDeLancienneFrance/Villes B/Bourbon/bourbon.html' },
        { name: 'Bourbon Lancy', url: '../../../laPosteDeLancienneFrance/Villes B/BourbonLancy/bourbonLancy.html' },
        { name: 'Bourbonne', url: '../../../laPosteDeLancienneFrance/Villes B/Bourbonne/bourbonne.html' },
        { name: 'Bourbourg', url: '../../../laPosteDeLancienneFrance/Villes B/Bourbourg/bourbourg.html' },
        { name: 'Bourdeilles', url: '../../../laPosteDeLancienneFrance/Villes B/Bourdeilles/bourdeilles.html' },
        { name: 'Bourg Argental', url: '../../../laPosteDeLancienneFrance/Villes B/BourgArgental/bourgArgental.html' },
        { name: 'Bourdon', url: '../../../laPosteDeLancienneFrance/Villes B/Bourdon/bourdon.html' },
        { name: 'Bourg D Oisans', url: '../../../laPosteDeLancienneFrance/Villes B/BourgDoisan/bourgDoisan.html' },
        { name: 'Bourg en Bresse', url: '../../../laPosteDeLancienneFrance/Villes B/BourgEnBresse/bourgEnBresse.html' },
        { name: 'Bourg en Guyenne', url: '../../../laPosteDeLancienneFrance/Villes B/BourgEnGuyenne/bourgEnGuyenne.html' },
        { name: 'Bourg la Reine', url: '../../../laPosteDeLancienneFrance/Villes B/BourgLaReine/bourgLaReine.html' },
        { name: 'Bourg St Andeol', url: '../../../laPosteDeLancienneFrance/Villes B/BourgStAndeol/bourgStAndeol.html' },
        { name: 'Bourgachard', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgachard/bourgachard.html' },
        { name: 'Bourganeuf', url: '../../../laPosteDeLancienneFrance/Villes B/Bourganeuf/bourganeuf.html' },
        { name: 'Bourges', url: '../../../laPosteDeLancienneFrance/Villes B/Bourges/bourges.html' },
        { name: 'Le bourget', url: '../../../laPosteDeLancienneFrance/Villes B/Bourget/bourget.html' },
        { name: 'Bourgneuf', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgneuf/bourgneuf.html' },
        { name: 'Bourgneuf en Retz', url: '../../../laPosteDeLancienneFrance/Villes B/BourgneufEnRetz/bourgneufEnRetz.html' },
        { name: 'Bourgoin', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgoin/bourgoin.html' },
        { name: 'Bourgtheroude', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgtheroulde/bourgtheroulde.html' },
        { name: 'Bourgueil', url: '../../../laPosteDeLancienneFrance/Villes B/Bourgueil/bourgueil.html' },
        { name: 'Bourmont', url: '../../../laPosteDeLancienneFrance/Villes B/Bourmont/bourmont.html' },
        { name: 'Boussac', url: '../../../laPosteDeLancienneFrance/Villes B/Boussac/boussac.html' },
        { name: 'Bouxwiller', url: '../../../laPosteDeLancienneFrance/Villes B/Bouxwiller/bouxwiller.html' },
        { name: 'Bouzonville', url: '../../../laPosteDeLancienneFrance/Villes B/Bouzonville/bouzonville.html' },
        { name: 'Boynes', url: '../../../laPosteDeLancienneFrance/Villes B/Boynes/boynes.html' },
        { name: 'Braisne', url: '../../../laPosteDeLancienneFrance/Villes B/Braisne/braisne.html' },
        { name: 'Bray sur Seine', url: '../../../laPosteDeLancienneFrance/Villes B/Bray/bray.html' },
        { name: 'Brecey', url: '../../../laPosteDeLancienneFrance/Villes B/Brecey/brecey.html' },
        { name: 'Bressuire', url: '../../../laPosteDeLancienneFrance/Villes B/Bressuire/bressuire.html' },
        { name: 'Brest', url: '../../../laPosteDeLancienneFrance/Villes B/Brest/brest.html' },
        { name: 'La Breteche', url: '../../../laPosteDeLancienneFrance/Villes B/Breteche/breteche.html' },
        { name: 'Breteuil (26)', url: '../../../laPosteDeLancienneFrance/Villes B/Breteuil26/breteuil26.html' },
        { name: 'Breteuil (58)', url: '../../../laPosteDeLancienneFrance/Villes B/Breteuil58/breteuil58.html' },
        { name: 'Brezolle', url: '../../../laPosteDeLancienneFrance/Villes B/Brezolle/brezolle.html' },
        { name: 'Briancon', url: '../../../laPosteDeLancienneFrance/Villes B/Briancon/briancon.html' },
        { name: 'Briare', url: '../../../laPosteDeLancienneFrance/Villes B/Briare/briare.html' },
        { name: 'Brie comte Robert', url: '../../../laPosteDeLancienneFrance/Villes B/Brie/brie.html' },
        { name: 'Brienne le Château', url: '../../../laPosteDeLancienneFrance/Villes B/Brienne/brienne.html' },
        { name: 'Brienon L Archeveque', url: '../../../laPosteDeLancienneFrance/Villes B/Brienon/brienon.html' },
        { name: 'Briey', url: '../../../laPosteDeLancienneFrance/Villes B/Briey/briey.html' },
        { name: 'Brignoles', url: '../../../laPosteDeLancienneFrance/Villes B/Brignoles/brignoles.html' },
        { name: 'Brillac', url: '../../../laPosteDeLancienneFrance/Villes B/Brillac/brillac.html' },
        { name: 'Brionne', url: '../../../laPosteDeLancienneFrance/Villes B/Brionne/brionne.html' },
        { name: 'Brioude', url: '../../../laPosteDeLancienneFrance/Villes B/Brioude/brioude.html' },
        { name: 'Brisach', url: '../../../laPosteDeLancienneFrance/Villes B/Brisach/brisach.html' },
        { name: 'Brissac', url: '../../../laPosteDeLancienneFrance/Villes B/Brissac/brissac.html' },
        { name: 'Brive', url: '../../../laPosteDeLancienneFrance/Villes B/Brive/brive.html' },
        { name: 'Broons', url: '../../../laPosteDeLancienneFrance/Villes B/Broons/broons.html' },
        { name: 'Brou', url: '../../../laPosteDeLancienneFrance/Villes B/Brou/brou.html' },
        { name: 'Brouage', url: '../../../laPosteDeLancienneFrance/Villes B/Brouage/brouage.html' },
        { name: 'Brunoy', url: '../../../laPosteDeLancienneFrance/Villes B/Brunoy/brunoy.html' },
        { name: 'Bruyeres', url: '../../../laPosteDeLancienneFrance/Villes B/Bruyeres/bruyeres.html' },
        { name: 'Buchy', url: '../../../laPosteDeLancienneFrance/Villes B/Buchy/buchy.html' },
        { name: 'Le Bugue', url: '../../../laPosteDeLancienneFrance/Villes B/Buis/buis.html' },
        { name: 'La Buissiere', url: '../../../laPosteDeLancienneFrance/Villes B/Buissieres/buissieres.html' },
        { name: 'Buzancais', url: '../../../laPosteDeLancienneFrance/Villes B/Buzancais/buzancais.html' },
        { name: 'Buzancy', url: '../../../laPosteDeLancienneFrance/Villes B/Buzancy/buzancy.html' },
        
        // Ajoutez d'autres villes ici
    ];

    // Initialisation des liens de ville
    for (var i = 0; i < cityLinks.length; i++) {
        var link = document.createElement('a');
        link.href = cityLinks[i].url;
        link.textContent = cityLinks[i].name;
        dropdownContent.appendChild(link);
    }

    input.addEventListener('input', function () {
        var filter = input.value.toLowerCase();
        var links = dropdownContent.getElementsByTagName('a');

        for (var i = 0; i < links.length; i++) {
            var city = links[i].textContent.toLowerCase();
            links[i].style.display = city.includes(filter) ? '' : 'none';
        }
    });

    dropdownContent.addEventListener('click', function (event) {
        var target = event.target;
        if (target.tagName === 'A') {
            villeLink.innerHTML = ' &emsp;&emsp;' + target.textContent + '<i class="fas fa-caret-down"></i>';
            window.location.href = target.href;
        }
    });
});