document.addEventListener('DOMContentLoaded', function () {
    var input = document.getElementById('villeInput');
    var dropdownContent = document.getElementById('dropdownContent');
    var villeLink = document.getElementById('villeLink');

    // Tableau de liens de villes
    var cityLinks = [
        { name: 'Baccarat',  url: '../../../laPosteDeLancienneFrance/Villes_B/Baccarat/baccarat.html' },
        { name: 'Bagneres_De_Bigorre', url: '../../../laPosteDeLancienneFrance/Villes_B/Bagneres_De_Bigorre/BagneresDeBigorre.html' },
        { name: 'Bagneres_De_Louchon', url: '../../../laPosteDeLancienneFrance/Villes_B/Bagneres_De_Louchon/bagneresDeLouchon.html' },
        { name: 'Bagnols', url: '../../../laPosteDeLancienneFrance/Villes_B/Bagnols/bagnols.html' },
        { name: 'Bailleul', url: '../../../laPosteDeLancienneFrance/Villes_B/Bailleul/bailleul.html' },
        { name: 'Bain', url: '../../../laPosteDeLancienneFrance/Villes_B/Bain/bain.html' },
        { name: 'Bains', url: '../../../laPosteDeLancienneFrance/Villes_B/Bains/bains.html' },
        { name: 'Baisieux', url: '../../../laPosteDeLancienneFrance/Villes_B/Baisieux/baisieux.html' },
        { name: 'Balleroy', url: '../../../laPosteDeLancienneFrance/Villes_B/Balleroy/balleroy.html' },
        { name: 'Bapaume', url: '../../../laPosteDeLancienneFrance/Villes_B/Bapaume/bapaume.html' },
        { name: 'Bar le Duc', url: '../../../laPosteDeLancienneFrance/Villes_B/BarLeDuc/barLeDuc.html' },
        { name: 'Bar sur Aube', url: '../../../laPosteDeLancienneFrance/Villes_B/BarSurAube/barSurAube.html' },
        { name: 'Bar sur Seine', url: '../../../laPosteDeLancienneFrance/Villes_B/BarSurSeine/barSurSeine.html' },
        { name: 'La Baraque sous Gevrey', url: '../../../laPosteDeLancienneFrance/Villes_B/baraque/Baraque.html' },
        { name: 'Barbencon', url: '../../../laPosteDeLancienneFrance/Villes_B/Barbencon/barbencon.html' },
        { name: 'Barbentane', url: '../../../laPosteDeLancienneFrance/Villes_B/Barbentane/barbentane.html' },
        { name: 'Barbezieux', url: '../../../laPosteDeLancienneFrance/Villes_B/Barbezieux/barbezieux.html' },
        { name: 'Barbonne', url: '../../../laPosteDeLancienneFrance/Villes_B/Barbonne/barbonne.html' },
        { name: 'Barcelonnette', url: '../../../laPosteDeLancienneFrance/Villes_B/Barcelonnette/barcelonette.html' },
        { name: 'Bareges', url: '../../../laPosteDeLancienneFrance/Villes_B/Bareges/bareges.html' },
        { name: 'Barentin', url: '../../../laPosteDeLancienneFrance/Villes_B/Barentin/barentin.html' },
        { name: 'Barjac', url: '../../../laPosteDeLancienneFrance/Villes_B/Barjac/barjac.html' },
        { name: 'Barjols', url: '../../../laPosteDeLancienneFrance/Villes_B/Barjols/barjols.html' },
        { name: 'Barraux', url: '../../../laPosteDeLancienneFrance/Villes_B/Barraux/barraux.html' },
        { name: 'La Barre', url: '../../../laPosteDeLancienneFrance/Villes_B/Barre/barre.html' },
        { name: 'Basses', url: '../../../laPosteDeLancienneFrance/Villes_B/Basses/bassee.html' },
        { name: 'Bassou', url: '../../../laPosteDeLancienneFrance/Villes_B/Bassou/bassou.html' },
        { name: 'Bastia', url: '../../../laPosteDeLancienneFrance/Villes_B/Bastia/bastia.html' },
        { name: 'Bauge', url: '../../../laPosteDeLancienneFrance/Villes_B/Bauge/bauge.html' },
        { name: 'Baume les Dames', url: '../../../laPosteDeLancienneFrance/Villes_B/Baume/baume.html' },
        { name: 'Bavay', url: '../../../laPosteDeLancienneFrance/Villes_B/Bavay/bavay.html' },
        { name: 'Bayeux', url: '../../../laPosteDeLancienneFrance/Villes_B/Bayeux/bayeux.html' },
        { name: 'Bayonne', url: '../../../laPosteDeLancienneFrance/Villes_B/Bayonne/bayonne.html' },
        { name: 'Bazas', url: '../../../laPosteDeLancienneFrance/Villes_B/Bazas/bazas.html' },
        { name: 'Beaucaire', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaucaire/beaucaire.html' },
        { name: 'Beaufort', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaufort/beaufort.html' },
        { name: 'Beaugency', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaugency/beaugency.html' },
        { name: 'Beaujeu', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaujeu/beaujeu.html' },
        { name: 'Beaulieu (36)', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaulieu36/beaulieu36.html' },
        { name: 'Beaulieu (18)', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaulieu18/beaulieu18.html' },
        { name: 'Beaulieu79', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaulieu79/beaulieu79.html' },
        { name: 'BeaumontDeLomagne', url: '../../../laPosteDeLancienneFrance/Villes_B/BeaumontDeLomagne/beaumontDeLomagne.html' },
        { name: 'BeaumontLeRoger', url: '../../../laPosteDeLancienneFrance/Villes_B/BeaumontLeRoger/beaumontLeRoger.html' },
        { name: 'BeaumontLeVicomte', url: '../../../laPosteDeLancienneFrance/Villes_B/BeaumontLeVicomte/beaumontLeVicomte.html' },
        { name: 'BeaumontSurOise', url: '../../../laPosteDeLancienneFrance/Villes_B/BeaumontSurOise/beaumontSurOise.html' },
        { name: 'Beaune', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaune/beaune.html' },
        { name: 'Beaupreau', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaupreau/beaupreau.html' },
        { name: 'Beaurepaire', url: '../../../laPosteDeLancienneFrance/Villes_B/Beaurepaire/beaurepaire.html' },
        { name: 'Le Beausset', url: '../../../laPosteDeLancienneFrance/Villes_B/Beausset/beausset.html' },
        { name: 'Beauvais', url: '../../../laPosteDeLancienneFrance/Villes_B/Beauvais/beauvais.html' },
        { name: 'Beauvoir sur mer', url: '../../../laPosteDeLancienneFrance/Villes_B/Beauvoir/beauvoir.html' },
        { name: 'Becherel', url: '../../../laPosteDeLancienneFrance/Villes_B/Becherel/becherel.html' },
        { name: 'Bedarieux', url: '../../../laPosteDeLancienneFrance/Villes_B/Bedarieux/bedarieux.html' },
        { name: 'Belfort', url: '../../../laPosteDeLancienneFrance/Villes_B/Belfort/belfort.html' },
        { name: 'Bellac', url: '../../../laPosteDeLancienneFrance/Villes_B/Bellac/bellac.html' },
        { name: 'BelleIsleEnMer', url: '../../../laPosteDeLancienneFrance/Villes_B/BelleIsleEnMer/belleIsleEnMer.html' },
        { name: 'Belle Isle en Terre', url: '../../../laPosteDeLancienneFrance/Villes_B/BelleIsleEnTerre/belleIsleEnTerre.html' },
        { name: 'Bellegarde', url: '../../../laPosteDeLancienneFrance/Villes_B/Bellegarde/bellegarde.html' },
        { name: 'Bellemare', url: '../../../laPosteDeLancienneFrance/Villes_B/Bellemare/bellemare.html' },
        { name: 'Belleme', url: '../../../laPosteDeLancienneFrance/Villes_B/Belleme/belleme.html' },
        { name: 'Belleville sur Saone', url: '../../../laPosteDeLancienneFrance/Villes_B/Belleville/belleville.html' },
        { name: 'Belley', url: '../../../laPosteDeLancienneFrance/Villes_B/Belley/belley.html' },
        { name: 'Belpech', url: '../../../laPosteDeLancienneFrance/Villes_B/Belpech/belpech.html' },
        { name: 'Belves', url: '../../../laPosteDeLancienneFrance/Villes_B/Belves/belves.html' },
        { name: 'Benfeld', url: '../../../laPosteDeLancienneFrance/Villes_B/Benfeld/benfeld.html' },
        { name: 'Bergerac', url: '../../../laPosteDeLancienneFrance/Villes_B/Bergerac/bergerac.html' },
        { name: 'Bergues', url: '../../../laPosteDeLancienneFrance/Villes_B/Bergues/bergues.html' },
        { name: 'Bernay', url: '../../../laPosteDeLancienneFrance/Villes_B/Bernay/bernay.html' },
        { name: 'Besancon', url: '../../../laPosteDeLancienneFrance/Villes_B/Besancon/besancon.html' },
        { name: 'Besse', url: '../../../laPosteDeLancienneFrance/Villes_B/Besse/besse.html' },
        { name: 'Bessines', url: '../../../laPosteDeLancienneFrance/Villes_B/Bessines/bessines.html' },
        { name: 'Bethleem', url: '../../../laPosteDeLancienneFrance/Villes_B/Bethleem/bethleem.html' },
        { name: 'Bethune', url: '../../../laPosteDeLancienneFrance/Villes_B/Bethune/bethune.html' },
        { name: 'Bezier', url: '../../../laPosteDeLancienneFrance/Villes_B/Beziers/beziers.html' },
        { name: 'Billom', url: '../../../laPosteDeLancienneFrance/Villes_B/Billom/billom.html' },
        { name: 'Binche', url: '../../../laPosteDeLancienneFrance/Villes_B/Binche/binche.html' },
        { name: 'Bitche', url: '../../../laPosteDeLancienneFrance/Villes_B/Bitche/bitche.html' },
        { name: 'Blain', url: '../../../laPosteDeLancienneFrance/Villes_B/Blain/blain.html' },
        { name: 'Blamont (24)', url: '../../../laPosteDeLancienneFrance/Villes_B/Blamont24/blamont24.html' },
        { name: 'Blamont (52)', url: '../../../laPosteDeLancienneFrance/Villes_B/Blamont52/blamont52.html' },
        { name: 'Le Blanc', url: '../../../laPosteDeLancienneFrance/Villes_B/Blanc/blanc.html' },
        { name: 'Blanzac', url: '../../../laPosteDeLancienneFrance/Villes_B/Blanzac/blanzac.html' },
        { name: 'Blaye', url: '../../../laPosteDeLancienneFrance/Villes_B/Blaye/blaye.html' },
        { name: 'Bleres', url: '../../../laPosteDeLancienneFrance/Villes_B/Bleres/bleres.html' },
        { name: 'Boen', url: '../../../laPosteDeLancienneFrance/Villes_B/Boen/boen.html' },
        { name: 'Blois', url: '../../../laPosteDeLancienneFrance/Villes_B/Blois/blois.html' },
        { name: 'Blosseville', url: '../../../laPosteDeLancienneFrance/Villes_B/Blosseville/blosseville.html' },
        { name: 'Besançon', url: '../../../laPosteDeLancienneFrance/Villes_B/Besançon/besançon.html' },
        { name: 'Boiscommun', url: '../../../laPosteDeLancienneFrance/Villes_B/Boiscommun/boiscommun.html' },
        { name: 'Boissy St Leger', url: '../../../laPosteDeLancienneFrance/Villes_B/Boissy/boissy.html' },
        { name: 'Bolbec', url: '../../../laPosteDeLancienneFrance/Villes_B/Bolbec/bolbec.html' },
        { name: 'Le Bolhard', url: '../../../laPosteDeLancienneFrance/Villes_B/Bolhard/bolhard.html' },
        { name: 'Boncourt', url: '../../../laPosteDeLancienneFrance/Villes_B/Boncourt/boncourt.html' },
        { name: 'Bondy', url: '../../../laPosteDeLancienneFrance/Villes_B/Bondy/bondy.html' },
        { name: 'Bonifacio', url: '../../../laPosteDeLancienneFrance/Villes_B/Bonifacio/bonifacio.html' },
        { name: 'Bonnelles', url: '../../../laPosteDeLancienneFrance/Villes_B/Bonnelles/bonnelles.html' },
        { name: 'Bonnetable', url: '../../../laPosteDeLancienneFrance/Villes_B/Bonnetable/bonnetable.html' },
        { name: 'Bonneval', url: '../../../laPosteDeLancienneFrance/Villes_B/Bonneval/bonneval.html' },
        { name: 'Bonnieres', url: '../../../laPosteDeLancienneFrance/Villes_B/Bonnieres/bonnieres.html' },
        { name: 'Bonny', url: '../../../laPosteDeLancienneFrance/Villes_B/Bonny/bonny.html' },
        { name: 'LeBordeauDeVigny', url: '../../../laPosteDeLancienneFrance/Villes_B/LeBordeauDeVigny/leBordeauDeVigny.html' },
        { name: 'Bordeaux', url: '../../../laPosteDeLancienneFrance/Villes_B/Bordeaux/bordeaux.html' },
        { name: 'Petite poste de Bordeaux', url: '../../../laPosteDeLancienneFrance/Villes_B/Bordeauxpp/bordeauxpp.html' },
        { name: 'Bort', url: '../../../laPosteDeLancienneFrance/Villes_B/Bort/bort.html' },
        { name: 'Bouchain', url: '../../../laPosteDeLancienneFrance/Villes_B/Bouchain/bouchain.html' },
        { name: 'Boucoiran', url: '../../../laPosteDeLancienneFrance/Villes_B/Boucoiran/boucoiran.html' },
        { name: 'Bouillon', url: '../../../laPosteDeLancienneFrance/Villes_B/Bouillon/bouillon.html' },
        { name: 'Boulay', url: '../../../laPosteDeLancienneFrance/Villes_B/Boulay/boulay.html' },
        { name: 'Boulogne', url: '../../../laPosteDeLancienneFrance/Villes_B/Boulogne/Boulogne.html' },
        { name: 'Boulogne sur Mer', url: '../../../laPosteDeLancienneFrance/Villes_B/BoulogneSurMer/boulogneSurMer.html' },
        { name: 'Boulou', url: '../../../laPosteDeLancienneFrance/Villes_B/Boulou/boulou.html' },
        { name: 'Bouquenon', url: '../../../laPosteDeLancienneFrance/Villes_B/Bouquenon/bouquenon.html' },
        { name: 'BourbonLarchambault', url: '../../../laPosteDeLancienneFrance/Villes_B/BourbonLarchambault/bourbonLarchambault.html' },
        { name: 'Bourbon Lancy', url: '../../../laPosteDeLancienneFrance/Villes_B/BourbonLancy/bourbonLancy.html' },
        { name: 'Bourbonne', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourbonne/bourbonne.html' },
        { name: 'Bourbourg', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourbourg/bourbourg.html' },
        { name: 'Bourdeilles', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourdeilles/bourdeilles.html' },
        { name: 'Bourg Argental', url: '../../../laPosteDeLancienneFrance/Villes_B/BourgArgental/bourgArgental.html' },
        { name: 'Bourdon', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourdon/bourdon.html' },
        { name: 'Bourg-Doisans', url: '../../../laPosteDeLancienneFrance/Villes_B/BourgDoisans/bourgDoisans.html' },
        { name: 'Bourg-En-Bresse', url: '../../../laPosteDeLancienneFrance/Villes_B/BourgEnBresse/bourgEnBresse.html' },
        { name: 'Bourg en Guyenne', url: '../../../laPosteDeLancienneFrance/Villes_B/BourgEnGuyenne/bourgEnGuyenne.html' },
        { name: 'Bourg la Reine', url: '../../../laPosteDeLancienneFrance/Villes_B/BourgLaReine/bourgLaReine.html' },
        { name: 'Bourg St Andeol', url: '../../../laPosteDeLancienneFrance/Villes_B/BourgStAndeol/bourgStAndeol.html' },
        { name: 'Bourgachard', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourgachard/bourgachard.html' },
        { name: 'Bourganeuf', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourganeuf/bourganeuf.html' },
        { name: 'Bourges', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourges/bourges.html' },
        { name: 'Le bourget', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourget/bourget.html' },
        { name: 'Bourgneuf', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourgneuf/bourgneuf.html' },
        { name: 'Bourgneuf en Retz', url: '../../../laPosteDeLancienneFrance/Villes_B/BourgneufEnRetz/bourgneufEnRetz.html' },
        { name: 'Bourgoin', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourgoin/bourgoin.html' },
        { name: 'Bourgthroulde', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourgthroulde/bourgtheroulde.html' },
        { name: 'Bourgueil', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourgueil/bourgueil.html' },
        { name: 'Bourmont', url: '../../../laPosteDeLancienneFrance/Villes_B/Bourmont/bourmont.html' },
        { name: 'Boussac', url: '../../../laPosteDeLancienneFrance/Villes_B/Boussac/boussac.html' },
        { name: 'Bouxwiller', url: '../../../laPosteDeLancienneFrance/Villes_B/Bouxwiller/bouxwiller.html' },
        { name: 'Bouzonville', url: '../../../laPosteDeLancienneFrance/Villes_B/Bouzonville/bouzonville.html' },
        { name: 'Boynes', url: '../../../laPosteDeLancienneFrance/Villes_B/Boynes/boynes.html' },
        { name: 'Braisne', url: '../../../laPosteDeLancienneFrance/Villes_B/Braisne/braisne.html' },
        { name: 'Bray sur Seine', url: '../../../laPosteDeLancienneFrance/Villes_B/Bray/bray.html' },
        { name: 'Brecey', url: '../../../laPosteDeLancienneFrance/Villes_B/Brecey/brecey.html' },
        { name: 'Bressuire', url: '../../../laPosteDeLancienneFrance/Villes_B/Bressuire/bressuire.html' },
        { name: 'Brest', url: '../../../laPosteDeLancienneFrance/Villes_B/Brest/brest.html' },
        { name: 'La Breteche', url: '../../../laPosteDeLancienneFrance/Villes_B/Breteche/breteche.html' },
        { name: 'Breteuil (26)', url: '../../../laPosteDeLancienneFrance/Villes_B/Breteuil26/breteuil26.html' },
        { name: 'Breteuil (58)', url: '../../../laPosteDeLancienneFrance/Villes_B/Breteuil58/breteuil58.html' },
        { name: 'Brezolles', url: '../../../laPosteDeLancienneFrance/Villes_B/Brezolles/brezolles.html' },
        { name: 'Briancon', url: '../../../laPosteDeLancienneFrance/Villes_B/Briancon/briancon.html' },
        { name: 'Briare', url: '../../../laPosteDeLancienneFrance/Villes_B/Briare/briare.html' },
        { name: 'Brie-Comte-Robert', url: '../../../laPosteDeLancienneFrance/Villes_B/Brie-Comte-Robert/brieComteRobert.html' },
        { name: 'Brienne le Château', url: '../../../laPosteDeLancienneFrance/Villes_B/Brienne/brienne.html' },
        { name: 'Brienon-L-Archeveque', url: '../../../laPosteDeLancienneFrance/Villes_B/Brienon-L-Archeveque/brienonLarcheveque.html' },
        { name: 'Briey', url: '../../../laPosteDeLancienneFrance/Villes_B/Briey/briey.html' },
        { name: 'Brignoles', url: '../../../laPosteDeLancienneFrance/Villes_B/Brignoles/brignoles.html' },
        { name: 'Brillac', url: '../../../laPosteDeLancienneFrance/Villes_B/Brillac/brillac.html' },
        { name: 'Brionne', url: '../../../laPosteDeLancienneFrance/Villes_B/Brionne/brionne.html' },
        { name: 'Brioude', url: '../../../laPosteDeLancienneFrance/Villes_B/Brioude/brioude.html' },
        { name: 'Brisach', url: '../../../laPosteDeLancienneFrance/Villes_B/Brisach/brisach.html' },
        { name: 'Brissac', url: '../../../laPosteDeLancienneFrance/Villes_B/Brissac/brissac.html' },
        { name: 'Brive', url: '../../../laPosteDeLancienneFrance/Villes_B/Brive/brive.html' },
        { name: 'Broons', url: '../../../laPosteDeLancienneFrance/Villes_B/Broons/broons.html' },
        { name: 'Brou', url: '../../../laPosteDeLancienneFrance/Villes_B/Brou/brou.html' },
        { name: 'Brouage', url: '../../../laPosteDeLancienneFrance/Villes_B/Brouage/brouage.html' },
        { name: 'Brunoy', url: '../../../laPosteDeLancienneFrance/Villes_B/Brunoy/brunoy.html' },
        { name: 'Bruyeres', url: '../../../laPosteDeLancienneFrance/Villes_B/Bruyeres/bruyeres.html' },
        { name: 'Buchy', url: '../../../laPosteDeLancienneFrance/Villes_B/Buchy/buchy.html' },
        { name: 'Le Bugue', url: '../../../laPosteDeLancienneFrance/Villes_B/Buis/buis.html' },
        { name: 'La Buissiere', url: '../../../laPosteDeLancienneFrance/Villes_B/Buissieres/buissieres.html' },
        { name: 'Buzancais', url: '../../../laPosteDeLancienneFrance/Villes_B/Buzancais/buzancais.html' },
        { name: 'Buzancy', url: '../../../laPosteDeLancienneFrance/Villes_B/Buzancy/buzancy.html' },
        { name: 'Buis', url: '../../../laPosteDeLancienneFrance/Villes_B/Buis/buis.html' },
        
        // Ajoutez d'autres villes ici
    ];

    // Initialisation des liens de ville
    for (var i = 0; i < cityLinks.length; i++) {
        var link = document.createElement('a');
        link.href = cityLinks[i].url;
        link.textContent = cityLinks[i].name;
        dropdownContent.appendChild(link);
    }

    input.addEventListener('input', function () {
        var filter = input.value.toLowerCase();
        var links = dropdownContent.getElementsByTagName('a');

        for (var i = 0; i < links.length; i++) {
            var city = links[i].textContent.toLowerCase();
            links[i].style.display = city.includes(filter) ? '' : 'none';
        }
    });

    dropdownContent.addEventListener('click', function (event) {
        var target = event.target;
        if (target.tagName === 'A') {
            villeLink.innerHTML = ' &emsp;&emsp;' + target.textContent + '<i class="fas fa-caret-down"></i>';
            window.location.href = target.href;
        }
    });
});